### ISSUE TITLE
index out of range panic

### ISSUE THREAD

**Issue by shpyntov** [ethersphere/bee#1340]
#### Summary
I had a crash of node, logs attached

#### Steps to reproduce
https://pastebin.com/raw/rVnHAVt1
https://pastebee.com/?05a3568672967385ab32a1ea0154a53596cc50ad188cc2116d5d1754f1b022e0

#### Expected behavior
node isn't crashing

#### Actual behavior
node is crashing

**Comment by Eknir** [comment]
Thanks for reporting this! We will have a look at this. Did you apply any special (non-default) configuration of your node? How did you install and run Bee? What version of Bee were you running?

**Comment by acud** [comment]
```
45c179bbcd6ae0ae1df1d7d29be4004763af6a10f7b8: context deadline exceeded 
panic: runtime error: slice bounds out of range [:16] with capacity 0

goroutine 5550134 [running]:
github.com/ethersphere/bee/pkg/localstore.New.func4(0xc009e12639, 0x20, 0x27, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/ethersphere/bee/pkg/localstore/localstore.go:233 +0xd1
github.com/ethersphere/bee/pkg/shed.Index.Get(0xc00040f5f0, 0xc000295c30, 0x1, 0x1, 0xc000c4fd40, 0xc000c77770, 0x16fbf78, 0x16fbf80, 0xc009e12639, 0x20, ...)
	github.com/ethersphere/bee/pkg/shed/index.go:154 +0x26d
github.com/ethersphere/bee/pkg/localstore.(*DB).setSync(0xc00010d800, 0xc00a57f840, 0xc009e12639, 0x20, 0x27, 0x0, 0x20, 0x40, 0xc800000000000000)
	github.com/ethersphere/bee/pkg/localstore/mode_set.go:134 +0x178
github.com/ethersphere/bee/pkg/localstore.(*DB).set(0xc00010d800, 0x0, 0xc0088faec0, 0x1, 0x1, 0x0, 0x0)
	github.com/ethersphere/bee/pkg/localstore/mode_set.go:64 +0x1af
github.com/ethersphere/bee/pkg/localstore.(*DB).Set(0xc00010d800, 0x185bd60, 0xc009942d80, 0x0, 0xc0088faec0, 0x1, 0x1, 0x0, 0x0)
	github.com/ethersphere/bee/pkg/localstore/mode_set.go:38 +0xf3
github.com/ethersphere/bee/pkg/pusher.(*Service).chunksWorker.func2(0xc000374f20, 0xc00000e4d0, 0xc000262c18, 0xc000cce180, 0xc0002ee360, 0x185bd60, 0xc009942d80, 0x1865e60, 0xc0062e2a00)
	github.com/ethersphere/bee/pkg/pusher/pusher.go:166 +0x248
created by github.com/ethersphere/bee/pkg/pusher.(*Service).chunksWorker
	github.com/ethersphere/bee/pkg/pusher/pusher.go:130 +0x68d
```
