### ISSUE TITLE
Feed lookup takes unreasonably long

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#1382]
In 0.5.1 the [Find feed update](https://docs.ethswarm.org/api/#tag/Feed/paths/~1feeds~1%7Bowner%7D~1%7Btopic%7D/get) endpoint returns the correct value.

However there are two new issues when using this feature:

1. After updating a feed and reading back the latest value immediately takes 10 seconds (the default chunk timeout) when running with multiple local nodes. This may not be a bug, just a lack of optimisation but it seems a bit weird from a user perspective. When running with a single, isolated node it returns almost instantly.

2. We have an [integration test](https://github.com/ethersphere/bee-js/blob/a5136590aa2de788ba1ab8f55f762f5e56f0f790/test/bee-class.spec.ts#L216) that does the operation described in point 1. twice. We run our tests on four different Node.js versions and out of 4 cases this test fails at least once randomly, by not finishing in 60 seconds. The 60 seconds were chosen with the timeout described in point 1. taken into consideration. This suggests that sometimes the lookups took even longer that 10 seconds or even they get stuck. This requires more investigation. Our [CI environment](https://github.com/ethersphere/bee-js/blob/fix/soc-upload-delete-chunk/.github/workflows/ci.yaml) is running a 5 node cluster with `bee-local` (which uses `beekeper` itself).

**Comment by agazso** [comment]
An update to the second point: after increasing the timeout from 60 seconds to 120 seconds the tests reliably run. This means that they don't get stuck, which is good news. However it would be good to investigate why they take so long.

**Comment by r0qs** [comment]
Hi @agazso could you please reproduce your test case using the branch of this PR: https://github.com/ethersphere/bee/pull/1548?

**Comment by agazso** [comment]
Hey @r0qs,

It's much better! Normally when everything works the test finishes in less than 3 seconds which would be more than acceptable for this kind of workload*.

However it crashes sometimes and the interesting thing is that there is always a feed lookup which takes 10 seconds before it crashes. I couldn't find any more clue what could possibly cause the crash besides this. Our tests are generating random keys (== random feeds) every time they run.

By the way let me know if you need help to set up the test environment the same way I test, it should be relatively straightforward if you already have `bee-js` cloned.

*The workload is the following by the way:

feed.upload() // == [find feed update](https://docs.ethswarm.org/api/#tag/Feed/paths/~1feeds~1{owner}~1{topic}/get), then [upload soc](https://docs.ethswarm.org/api/#tag/Single-owner-chunk/paths/~1soc~1{owner}~1{id}/post)
feed.download() // == [find feed update](https://docs.ethswarm.org/api/#tag/Feed/paths/~1feeds~1{owner}~1{topic}/get)
feed.upload() // see above
feed.download() // see above

Here is a log excerpt when it crashes:
```
DEBU[2021-04-20T17:19:19+02:00] retrieval headers: returned target de6bedf4244d5194364790c2eedd880663948464217050fa1170e9b57b60297f with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:19+02:00] retrieval headers: original target de6bedf4244d5194364790c2eedd880663948464217050fa1170e9b57b60297f with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:19+02:00] retrieval: failed to get chunk de6bedf4244d5194364790c2eedd880663948464217050fa1170e9b57b60297f from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c: read delivery: stream reset peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:19+02:00] retrieval headers: returned target de6bedf4244d5194364790c2eedd880663948464217050fa1170e9b57b60297f with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:19+02:00] retrieval headers: original target de6bedf4244d5194364790c2eedd880663948464217050fa1170e9b57b60297f with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:19+02:00] price headler: received target de6bedf4244d5194364790c2eedd880663948464217050fa1170e9b57b60297f with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:19+02:00] price headler: response target de6bedf4244d5194364790c2eedd880663948464217050fa1170e9b57b60297f with price as 0, for peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval: failed to get chunk de6bedf4244d5194364790c2eedd880663948464217050fa1170e9b57b60297f from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e: read delivery: context deadline exceeded peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] feed get: no update found: <nil>             
ERRO[2021-04-20T17:19:29+02:00] feed get: no update found                    
DEBU[2021-04-20T17:19:29+02:00] could not handle protocol retrieval/1.0.0: stream retrieval: peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c: error: retrieve chunk: storage: not found 
INFO[2021-04-20T17:19:29+02:00] api access                                    duration=10.002517718 ip=127.0.0.1 method=GET proto=HTTP/1.1 size=40 status=404 uri="/feeds/8d3766440f0d7b949a5e32995d09619a7f86e632/f35fed1a59c0d71aeb3e7254b0ced122ec0a893da1ad29410e14be2c2fbd58de?type=sequence" user-agent=axios/0.21.1
INFO[2021-04-20T17:19:29+02:00] api access                                    duration=0.001522022 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=82 status=201 uri="/soc/8d3766440f0d7b949a5e32995d09619a7f86e632/04ada8e2be4f3bc11db6f5b94d2b01577bf5348234725eed091efe0a6ad72c22?sig=be8d830081083a8a14621a9e1743c8486aa1ff3bf4501c7376844b4a3b766a614f1ca8732edc505004cdd82c2941957fff2838d7bcbbb41f7024b0beadc48d5e1b" user-agent=axios/0.21.1
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: returned target 30c15e166f519806d447c1db892651fd886e9b1d6f8ffca7ce499e9b5f40a688 with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: original target 30c15e166f519806d447c1db892651fd886e9b1d6f8ffca7ce499e9b5f40a688 with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: returned target 1688fc5bf7d204d975bf8d7c203f4e1e989dbf02ea5735bb792a9ce831e51ceb with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: original target 1688fc5bf7d204d975bf8d7c203f4e1e989dbf02ea5735bb792a9ce831e51ceb with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: returned target 067d4691cfd34445fb3ba4acf7d4c1b36b0cf66f4b38dc66e2b1d45831f2abc0 with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: original target 067d4691cfd34445fb3ba4acf7d4c1b36b0cf66f4b38dc66e2b1d45831f2abc0 with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: returned target e4021cc329a670e70aa66ee62df6f1b0f5de11b4e38a7c560a52321b10619225 with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: original target e4021cc329a670e70aa66ee62df6f1b0f5de11b4e38a7c560a52321b10619225 with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: returned target 9a5c82e7411fd93af5ef00ac663c86e9f451b885236e05dcebff11262ce72068 with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: original target 9a5c82e7411fd93af5ef00ac663c86e9f451b885236e05dcebff11262ce72068 with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: returned target f2cfa043a9577908c12e671f59fdfe78bf8e6c8975a44f5fa79575a327dead64 with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: original target f2cfa043a9577908c12e671f59fdfe78bf8e6c8975a44f5fa79575a327dead64 with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: returned target d05145cd26eeca5749d521a60b67e333995a27a3a1e081e7a137a85a041f0af4 with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: original target d05145cd26eeca5749d521a60b67e333995a27a3a1e081e7a137a85a041f0af4 with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: returned target e91705458649b2502107aecb940cd0a2abeb2f4a411037ae84b010e90ee89b03 with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: original target e91705458649b2502107aecb940cd0a2abeb2f4a411037ae84b010e90ee89b03 with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval: failed to get chunk d05145cd26eeca5749d521a60b67e333995a27a3a1e081e7a137a85a041f0af4 from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c: read delivery: stream reset peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval: failed to get chunk 067d4691cfd34445fb3ba4acf7d4c1b36b0cf66f4b38dc66e2b1d45831f2abc0 from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e: read delivery: stream reset peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval: failed to get chunk e91705458649b2502107aecb940cd0a2abeb2f4a411037ae84b010e90ee89b03 from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c: read delivery: stream reset peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval: failed to get chunk 1688fc5bf7d204d975bf8d7c203f4e1e989dbf02ea5735bb792a9ce831e51ceb from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e: read delivery: stream reset peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval: failed to get chunk e4021cc329a670e70aa66ee62df6f1b0f5de11b4e38a7c560a52321b10619225 from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c: read delivery: stream reset peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval: failed to get chunk f2cfa043a9577908c12e671f59fdfe78bf8e6c8975a44f5fa79575a327dead64 from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c: read delivery: stream reset peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval: failed to get chunk 9a5c82e7411fd93af5ef00ac663c86e9f451b885236e05dcebff11262ce72068 from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e: read delivery: stream reset peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval: failed to get chunk 30c15e166f519806d447c1db892651fd886e9b1d6f8ffca7ce499e9b5f40a688 from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e: read delivery: stream reset peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: returned target 9a5c82e7411fd93af5ef00ac663c86e9f451b885236e05dcebff11262ce72068 with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: original target 9a5c82e7411fd93af5ef00ac663c86e9f451b885236e05dcebff11262ce72068 with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: returned target 30c15e166f519806d447c1db892651fd886e9b1d6f8ffca7ce499e9b5f40a688 with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: original target 30c15e166f519806d447c1db892651fd886e9b1d6f8ffca7ce499e9b5f40a688 with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: returned target e91705458649b2502107aecb940cd0a2abeb2f4a411037ae84b010e90ee89b03 with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: returned target 067d4691cfd34445fb3ba4acf7d4c1b36b0cf66f4b38dc66e2b1d45831f2abc0 with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: original target 067d4691cfd34445fb3ba4acf7d4c1b36b0cf66f4b38dc66e2b1d45831f2abc0 with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: original target e91705458649b2502107aecb940cd0a2abeb2f4a411037ae84b010e90ee89b03 with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: returned target f2cfa043a9577908c12e671f59fdfe78bf8e6c8975a44f5fa79575a327dead64 with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: original target f2cfa043a9577908c12e671f59fdfe78bf8e6c8975a44f5fa79575a327dead64 with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: returned target 1688fc5bf7d204d975bf8d7c203f4e1e989dbf02ea5735bb792a9ce831e51ceb with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: original target 1688fc5bf7d204d975bf8d7c203f4e1e989dbf02ea5735bb792a9ce831e51ceb with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: returned target e4021cc329a670e70aa66ee62df6f1b0f5de11b4e38a7c560a52321b10619225 with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: original target e4021cc329a670e70aa66ee62df6f1b0f5de11b4e38a7c560a52321b10619225 with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: returned target d05145cd26eeca5749d521a60b67e333995a27a3a1e081e7a137a85a041f0af4 with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval headers: original target d05145cd26eeca5749d521a60b67e333995a27a3a1e081e7a137a85a041f0af4 with price as 0, from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval: failed to get chunk e91705458649b2502107aecb940cd0a2abeb2f4a411037ae84b010e90ee89b03 from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e: read delivery: stream reset peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
DEBU[2021-04-20T17:19:29+02:00] retrieval: failed to get chunk 30c15e166f519806d447c1db892651fd886e9b1d6f8ffca7ce499e9b5f40a688 from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c: read delivery: stream reset peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval: failed to get chunk 1688fc5bf7d204d975bf8d7c203f4e1e989dbf02ea5735bb792a9ce831e51ceb from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c: read delivery: stream reset peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval: failed to get chunk 067d4691cfd34445fb3ba4acf7d4c1b36b0cf66f4b38dc66e2b1d45831f2abc0 from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c: read delivery: stream reset peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval: failed to get chunk 9a5c82e7411fd93af5ef00ac663c86e9f451b885236e05dcebff11262ce72068 from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c: read delivery: stream reset peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] price headler: received target f2cfa043a9577908c12e671f59fdfe78bf8e6c8975a44f5fa79575a327dead64 with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] price headler: response target f2cfa043a9577908c12e671f59fdfe78bf8e6c8975a44f5fa79575a327dead64 with price as 0, for peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] price headler: received target d05145cd26eeca5749d521a60b67e333995a27a3a1e081e7a137a85a041f0af4 with price as 0, from peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] price headler: response target d05145cd26eeca5749d521a60b67e333995a27a3a1e081e7a137a85a041f0af4 with price as 0, for peer e424551647df0ac3db7cfb3546c78a07c087867c31aa455bc5eb4e74d3fc242c 
DEBU[2021-04-20T17:19:29+02:00] retrieval: failed to get chunk e4021cc329a670e70aa66ee62df6f1b0f5de11b4e38a7c560a52321b10619225 from peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e: read delivery: stream reset peer 8636ea383bfb3f3c303157dc33d33c7ca0c3fc54ec3e97a8eaec569511317d6e 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1dae7f1]

goroutine 6622 [running]:
github.com/ethersphere/bee/pkg/pusher.(*Service).chunksWorker.func2(0xc0000d4780, 0xc00000e008, 0xc00047a000, 0xc0012c4030, 0xc00028a060, 0x244f000, 0xc00110ca20, 0x2459400, 0xc000446c00)
	github.com/ethersphere/bee/pkg/pusher/pusher.go:174 +0x1b1
created by github.com/ethersphere/bee/pkg/pusher.(*Service).chunksWorker
	github.com/ethersphere/bee/pkg/pusher/pusher.go:136 +0x68d

```

**Comment by r0qs** [comment]
Hey thanks for the details, I'll try to reproduce it here.

By the way, this crash seems to be because the `receipt` is nil in the return of the `PushChunkToClosest` function. I believe this problem was solved [here](https://github.com/ethersphere/bee/blob/2c8c063259a9b9a6f92f91c9682e692dd2f92bbe/pkg/pusher/pusher.go#L176) but my branch was not updated.

I just update it now, sorry for that :)

Another thing, is that my branch currently has a hardcoded timeout of 1sec.
The idea is that the lookup must return if the feed can be found or if a timeout happen or if the parent process kill the lookup workers.

**Comment by agazso** [comment]
I tried out the updated branch and it no longer crashes, so this is already very good.

When trying to run the same test 10 times, in 2 cases it took more than 10 seconds. In the rest of the cases it ran less than 3-4 seconds. When it takes more than 10 seconds as far as I can see it's the first feed lookup that is blocking for 10 seconds. I have a hunch that this is caused by the the [chunk retrieval timeout](https://github.com/ethersphere/bee/blob/master/pkg/retrieval/retrieval.go#L182) and I think it would be good to investigate and understand under what circumstances this happens and how does this work in relationship with the feed lookup timeout.

**Comment by Eknir** [comment]
@agazso , changes were made with #1548 , could you please report if these improve the situation up to a reasonable standard?
