### ISSUE TITLE
Chunk upload panics

### ISSUE THREAD

**Issue by svetomir** [ethersphere/bee#151]
Chunk upload (POST http://bee-0.svetomir.core.internal/bzz/) panics with traceback bellow.
It can be seen from traces that slicing in validator is incorrect.

```
time="2020-05-04T13:53:25Z" level=error msg="http: panic serving 10.0.64.26:60246: runtime error: slice bounds out of range [8:5]"
time="2020-05-04T13:53:25Z" level=error msg="goroutine 19123 [running]:"
time="2020-05-04T13:53:25Z" level=error msg="net/http.(*conn).serve.func1(0xc0000b88c0)"
time="2020-05-04T13:53:25Z" level=error msg="\tnet/http/server.go:1772 +0x139"
time="2020-05-04T13:53:25Z" level=error msg="panic(0xf0a420, 0xc000c174a0)"
time="2020-05-04T13:53:25Z" level=error msg="\truntime/panic.go:975 +0x3e3"
time="2020-05-04T13:53:25Z" level=error msg="github.com/ethersphere/bee/pkg/validator.(*ContentAddressValidator).Validate(0xc000c32880, 0x123a380, 0xc000bb6280, 0x2)"
time="2020-05-04T13:53:25Z" level=error msg="\tgithub.com/ethersphere/bee/pkg/validator/validator.go:56 +0x331"
time="2020-05-04T13:53:25Z" level=error msg="github.com/ethersphere/bee/pkg/netstore.(*store).valid(0xc0000aec40, 0x123a380, 0xc000bb6280, 0x0)"
time="2020-05-04T13:53:25Z" level=error msg="\tgithub.com/ethersphere/bee/pkg/netstore/netstore.go:75 +0x7a"
time="2020-05-04T13:53:25Z" level=error msg="github.com/ethersphere/bee/pkg/netstore.(*store).Put(0xc0000aec40, 0x1235400, 0xc001314120, 0x2, 0xc000041770, 0x1, 0x1, 0x10, 0x9ed1c8, 0x9ed0ff, ...)"
time="2020-05-04T13:53:25Z" level=error msg="\tgithub.com/ethersphere/bee/pkg/netstore/netstore.go:65 +0x79"
time="2020-05-04T13:53:25Z" level=error msg="github.com/ethersphere/bee/pkg/api.(*server).bzzUploadHandler(0xc0001d7a80, 0x1230300, 0xc000080960, 0xc0001d3000)"
time="2020-05-04T13:53:25Z" level=error msg="\tgithub.com/ethersphere/bee/pkg/api/bzz.go:64 +0x63e"
time="2020-05-04T13:53:25Z" level=error msg="net/http.HandlerFunc.ServeHTTP(0xc000c34d90, 0x1230300, 0xc000080960, 0xc0001d3000)"
time="2020-05-04T13:53:25Z" level=error msg="\tnet/http/server.go:2012 +0x44"
time="2020-05-04T13:53:25Z" level=error msg="resenje.org/web.HandleMethods(0xc000c40030, 0xfb53b1, 0x2b, 0xfa68f4, 0x1f, 0x1230300, 0xc000080960, 0xc0001d3000)"
time="2020-05-04T13:53:25Z" level=error msg="\tresenje.org/web@v0.4.0/method.go:20 +0x5d0"
time="2020-05-04T13:53:25Z" level=error msg="github.com/ethersphere/bee/pkg/jsonhttp.MethodHandler.ServeHTTP(0xc000c40030, 0x1230300, 0xc000080960, 0xc0001d3000)"
time="2020-05-04T13:53:25Z" level=error msg="\tgithub.com/ethersphere/bee/pkg/jsonhttp/handlers.go:16 +0x76"
time="2020-05-04T13:53:25Z" level=error msg="github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001f4180, 0x1230300, 0xc000080960, 0xc00141d600)"
time="2020-05-04T13:53:25Z" level=error msg="\tgithub.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2"
time="2020-05-04T13:53:25Z" level=error msg="github.com/ethersphere/bee/pkg/api.(*server).pageviewMetricsHandler.func1(0x1230300, 0xc000080960, 0xc00141d600)"
time="2020-05-04T13:53:25Z" level=error msg="\tgithub.com/ethersphere/bee/pkg/api/metrics.go:58 +0xa7"
time="2020-05-04T13:53:25Z" level=error msg="net/http.HandlerFunc.ServeHTTP(0xc000c32d00, 0x1230300, 0xc000080960, 0xc00141d600)"
time="2020-05-04T13:53:25Z" level=error msg="\tnet/http/server.go:2012 +0x44"
time="2020-05-04T13:53:25Z" level=error msg="github.com/gorilla/handlers.CompressHandlerLevel.func1(0x122fcc0, 0xc00018bca0, 0xc00141d600)"
time="2020-05-04T13:53:25Z" level=error msg="\tgithub.com/gorilla/handlers@v1.4.2/compress.go:148 +0x17b"
time="2020-05-04T13:53:25Z" level=error msg="net/http.HandlerFunc.ServeHTTP(0xc000c32d20, 0x122fcc0, 0xc00018bca0, 0xc00141d600)"
time="2020-05-04T13:53:25Z" level=error msg="\tnet/http/server.go:2012 +0x44"
time="2020-05-04T13:53:25Z" level=error msg="github.com/ethersphere/bee/pkg/logging.NewHTTPAccessLogHandler.func1.1(0x1232240, 0xc001349340, 0xc00141d600)"
time="2020-05-04T13:53:25Z" level=error msg="\tgithub.com/ethersphere/bee/pkg/logging/http_access.go:21 +0x117"
time="2020-05-04T13:53:25Z" level=error msg="net/http.HandlerFunc.ServeHTTP(0xc0000aed40, 0x1232240, 0xc001349340, 0xc00141d600)"
time="2020-05-04T13:53:25Z" level=error msg="\tnet/http/server.go:2012 +0x44"
time="2020-05-04T13:53:25Z" level=error msg="net/http.serverHandler.ServeHTTP(0xc00007a540, 0x1232240, 0xc001349340, 0xc00141d600)"
time="2020-05-04T13:53:25Z" level=error msg="\tnet/http/server.go:2807 +0xa3"
time="2020-05-04T13:53:25Z" level=error msg="net/http.(*conn).serve(0xc0000b88c0, 0x1235340, 0xc000260340)"
time="2020-05-04T13:53:25Z" level=error msg="\tnet/http/server.go:1895 +0x86c"
time="2020-05-04T13:53:25Z" level=error msg="created by net/http.(*Server).Serve"
time="2020-05-04T13:53:25Z" level=error msg="\tnet/http/server.go:2933 +0x35c"
```

**Comment by acud** [comment]
What's the payload you're uploading?

**Comment by svetomir** [comment]
Simple 5bytes file with one word (5 characters) in it.

**Comment by acud** [comment]
OK.
It would be nice if when we have bug reports then to have `steps to reproduce`. It is still unclear how do you upload the file, do you use some custom go implementation, or just `curl`. Can you please include the steps to reproduce?
