### ISSUE TITLE
Deadlock in TestSplitterJobVector

### ISSUE THREAD

**Issue by janos** [ethersphere/bee#170]
Test TestSplitterJobVector timed out after 10 minutes in CI https://github.com/ethersphere/bee/runs/656113386#step:11:157. It looks like a possible deadlock.

```
2020-05-08T11:21:02.2561090Z === RUN   TestSplitterJobVector
2020-05-08T11:21:02.2562010Z === RUN   TestSplitterJobVector/31/ece86edb20669cc60d142789d464d57bdf5e33cb789d443f608cbd81cfa5697d
2020-05-08T11:21:02.2562700Z === RUN   TestSplitterJobVector/32/0be77f0bb7abc9cd0abed640ee29849a3072ccfd1020019fe03658c38f087e02
2020-05-08T11:21:02.2563120Z === RUN   TestSplitterJobVector/33/3463b46d4f9d5bfcbf9a23224d635e51896c1daef7d225b86679db17c5fd868e
2020-05-08T11:21:02.2585410Z === RUN   TestSplitterJobVector/63/95510c2ff18276ed94be2160aed4e69c9116573b6f69faaeed1b426fea6a3db8
2020-05-08T11:21:02.2585760Z === RUN   TestSplitterJobVector/64/490072cc55b8ad381335ff882ac51303cc069cbcb8d8d3f7aa152d9c617829fe
2020-05-08T11:21:02.2586360Z === RUN   TestSplitterJobVector/65/541552bae05e9a63a6cb561f69edf36ffe073e441667dbf7a0e9a3864bb744ea
2020-05-08T11:21:02.2587360Z === RUN   TestSplitterJobVector/4096/c10090961e7682a10890c334d759a28426647141213abda93b096b892824d2ef
2020-05-08T11:21:02.2587800Z === RUN   TestSplitterJobVector/4127/91699c83ed93a1f87e326a29ccd8cc775323f9e7260035a5f014c975c5f3cd28
2020-05-08T11:21:02.2588390Z === RUN   TestSplitterJobVector/4128/73759673a52c1f1707cbb61337645f4fcbd209cdc53d7e2cedaaa9f44df61285
2020-05-08T11:21:02.2588730Z === RUN   TestSplitterJobVector/4159/db1313a727ffc184ae52a70012fbbf7235f551b9f2d2da04bf476abe42a3cb42
2020-05-08T11:21:02.2589410Z === RUN   TestSplitterJobVector/4160/ade7af36ac0c7297dc1c11fd7b46981b629c6077bce75300f85b02a6153f161b
2020-05-08T11:21:02.2589830Z === RUN   TestSplitterJobVector/8192/29a5fb121ce96194ba8b7b823a1f9c6af87e1791f824940a53b5a7efe3f790d9
2020-05-08T11:21:02.2590410Z === RUN   TestSplitterJobVector/8224/61416726988f77b874435bdd89a419edc3861111884fd60e8adf54e2f299efd6
2020-05-08T11:21:02.2591410Z === RUN   TestSplitterJobVector/524288/3047d841077898c26bbe6be652a2ec590a5d9bd7cd45d290ea42511b48753c09
2020-05-08T11:21:02.2592120Z === RUN   TestSplitterJobVector/524319/e5c76afa931e33ac94bce2e754b1bb6407d07f738f67856783d93934ca8fc576
2020-05-08T11:21:02.2593010Z === RUN   TestSplitterJobVector/524320/485a526fc74c8a344c43a4545a5987d17af9ab401c0ef1ef63aefcc5c2c086df
2020-05-08T11:21:02.2593620Z === RUN   TestSplitterJobVector/524352/624b2abb7aefc0978f891b2a56b665513480e5dc195b4a66cd8def074a6d2e94
2020-05-08T11:21:02.2593900Z === RUN   TestSplitterJobVector/528384/b8e1804e37a064d28d161ab5f256cc482b1423d5cd0a6b30fde7b0f51ece9199
2020-05-08T11:21:02.2595780Z === RUN   TestSplitterJobVector/532480/59de730bf6c67a941f3b2ffa2f920acfaa1713695ad5deea12b4a121e5f23fa1
2020-05-08T11:21:02.2597100Z === RUN   TestSplitterJobVector/67108864/522194562123473dcfd7a457b18ee7dee8b7db70ed3cfa2b73f348a992fdfd3b
2020-05-08T11:21:02.2597510Z === RUN   TestSplitterJobVector/67108896/ed0cc44c93b14fef2d91ab3a3674eeb6352a42ac2f0bbe524711824aae1e7bcc
2020-05-08T11:21:02.2597800Z panic: test timed out after 10m0s
2020-05-08T11:21:02.2597970Z 
2020-05-08T11:21:02.2598130Z goroutine 1910343 [running]:
2020-05-08T11:21:02.2598890Z testing.(*M).startAlarm.func1()
2020-05-08T11:21:02.2599730Z 	/Users/runner/hostedtoolcache/go/1.14.2/x64/src/testing/testing.go:1459 +0x11c
2020-05-08T11:21:02.2600040Z created by time.goFunc
2020-05-08T11:21:02.2600560Z 	/Users/runner/hostedtoolcache/go/1.14.2/x64/src/time/sleep.go:168 +0x52
2020-05-08T11:21:02.2600980Z 
2020-05-08T11:21:02.2601490Z goroutine 1 [chan receive, 9 minutes]:
2020-05-08T11:21:02.2601830Z testing.(*T).Run(0xc00015e000, 0x1271089, 0x15, 0x1278610, 0x1)
2020-05-08T11:21:02.2602070Z 	/Users/runner/hostedtoolcache/go/1.14.2/x64/src/testing/testing.go:1043 +0x699
2020-05-08T11:21:02.2602370Z testing.runTests.func1(0xc00015e000)
2020-05-08T11:21:02.2602810Z 	/Users/runner/hostedtoolcache/go/1.14.2/x64/src/testing/testing.go:1284 +0xa7
2020-05-08T11:21:02.2603090Z testing.tRunner(0xc00015e000, 0xc00013fd50)
2020-05-08T11:21:02.2603650Z 	/Users/runner/hostedtoolcache/go/1.14.2/x64/src/testing/testing.go:991 +0x1ec
2020-05-08T11:21:02.2604170Z testing.runTests(0xc000134040, 0x13ed000, 0x2, 0x2, 0x0)
2020-05-08T11:21:02.2604540Z 	/Users/runner/hostedtoolcache/go/1.14.2/x64/src/testing/testing.go:1282 +0x528
2020-05-08T11:21:02.2605010Z testing.(*M).Run(0xc00015a000, 0x0)
2020-05-08T11:21:02.2605300Z 	/Users/runner/hostedtoolcache/go/1.14.2/x64/src/testing/testing.go:1199 +0x300
2020-05-08T11:21:02.2605790Z main.main()
2020-05-08T11:21:02.2606420Z 	_testmain.go:48 +0x224
2020-05-08T11:21:02.2606500Z 
2020-05-08T11:21:02.2606990Z goroutine 22 [chan receive, 5 minutes]:
2020-05-08T11:21:02.2607280Z testing.(*T).Run(0xc00015e240, 0xc00001a460, 0x49, 0x1278618, 0x1)
2020-05-08T11:21:02.2608110Z 	/Users/runner/hostedtoolcache/go/1.14.2/x64/src/testing/testing.go:1043 +0x699
2020-05-08T11:21:02.2608500Z github.com/ethersphere/bee/pkg/file/splitter/internal_test.TestSplitterJobVector(0xc00015e240)
2020-05-08T11:21:02.2609190Z 	/Users/runner/runners/2.169.1/work/bee/bee/pkg/file/splitter/internal/job_test.go:111 +0x11c
2020-05-08T11:21:02.2609740Z testing.tRunner(0xc00015e240, 0x1278610)
2020-05-08T11:21:02.2610090Z 	/Users/runner/hostedtoolcache/go/1.14.2/x64/src/testing/testing.go:991 +0x1ec
2020-05-08T11:21:02.2610630Z created by testing.(*T).Run
2020-05-08T11:21:02.2617160Z 	/Users/runner/hostedtoolcache/go/1.14.2/x64/src/testing/testing.go:1042 +0x661
2020-05-08T11:21:02.2617330Z 
2020-05-08T11:21:02.2617480Z goroutine 1911263 [runnable]:
2020-05-08T11:21:02.2618430Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc00011e330, 0x3a, 0xc001b61780, 0x40, 0x40, 0x1)
2020-05-08T11:21:02.2618760Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:462
2020-05-08T11:21:02.2619020Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-05-08T11:21:02.2619580Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:360 +0x41c
2020-05-08T11:21:02.2620190Z 
2020-05-08T11:21:02.2620580Z goroutine 1124349 [runnable]:
2020-05-08T11:21:02.2621180Z github.com/ethersphere/bmt/legacy.(*Hasher).write(0xc00011e330, 0xc0055358e0, 0x1000, 0x7720, 0xc00019e288)
2020-05-08T11:21:02.2621770Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:362 +0x43b
2020-05-08T11:21:02.2622370Z github.com/ethersphere/bmt/legacy.(*Hasher).Write(0xc00011e330, 0xc0055358e0, 0x1000, 0x7720, 0xc0003da640, 0x10a5db2, 0x1081b9e)
2020-05-08T11:21:02.2623140Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:321 +0x57
2020-05-08T11:21:02.2624420Z github.com/ethersphere/bee/pkg/file/splitter/internal.(*SimpleSplitterJob).sumLevel(0xc00553e000, 0x0, 0x7720, 0xc00ae90000, 0x1000, 0x1116020, 0x1)
2020-05-08T11:21:02.2625110Z 	/Users/runner/runners/2.169.1/work/bee/bee/pkg/file/splitter/internal/job.go:136 +0x4d7
2020-05-08T11:21:02.2625580Z github.com/ethersphere/bee/pkg/file/splitter/internal.(*SimpleSplitterJob).writeToLevel(0xc00553e000, 0x0, 0xc00ae90000, 0x1000, 0x1116020, 0x0, 0x0)
2020-05-08T11:21:02.2626650Z 	/Users/runner/runners/2.169.1/work/bee/bee/pkg/file/splitter/internal/job.go:108 +0x311
2020-05-08T11:21:02.2627340Z github.com/ethersphere/bee/pkg/file/splitter/internal.(*SimpleSplitterJob).Write(0xc00553e000, 0xc00ae90000, 0x1000, 0x1116020, 0x1000, 0x0, 0x0)
2020-05-08T11:21:02.2627730Z 	/Users/runner/runners/2.169.1/work/bee/bee/pkg/file/splitter/internal/job.go:76 +0x1cf
2020-05-08T11:21:02.2628260Z github.com/ethersphere/bee/pkg/file/splitter/internal_test.testSplitterJobVector(0xc00015e120)
2020-05-08T11:21:02.2628800Z 	/Users/runner/runners/2.169.1/work/bee/bee/pkg/file/splitter/internal/job_test.go:138 +0x443
2020-05-08T11:21:02.2629060Z testing.tRunner(0xc00015e120, 0x1278618)
2020-05-08T11:21:02.2629280Z 	/Users/runner/hostedtoolcache/go/1.14.2/x64/src/testing/testing.go:991 +0x1ec
2020-05-08T11:21:02.2629770Z created by testing.(*T).Run
2020-05-08T11:21:02.2630030Z 	/Users/runner/hostedtoolcache/go/1.14.2/x64/src/testing/testing.go:1042 +0x661
2020-05-08T11:21:02.2630600Z 
2020-05-08T11:21:02.2631120Z goroutine 1911264 [runnable]:
2020-05-08T11:21:02.2631530Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc00011e330, 0x3b, 0xc001b617c0, 0x40, 0x40, 0x1)
2020-05-08T11:21:02.2631890Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:462
2020-05-08T11:21:02.2632400Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-05-08T11:21:02.2632980Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:360 +0x41c
2020-05-08T11:21:02.2633080Z 
2020-05-08T11:21:02.2633350Z goroutine 1911265 [runnable]:
2020-05-08T11:21:02.2633960Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc00011e330, 0x3c, 0xc001b61800, 0x40, 0x40, 0x1)
2020-05-08T11:21:02.2634630Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:462
2020-05-08T11:21:02.2635740Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-05-08T11:21:02.2636760Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:360 +0x41c
2020-05-08T11:21:02.2636890Z 
2020-05-08T11:21:02.2637430Z goroutine 1911261 [runnable]:
2020-05-08T11:21:02.2638310Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc00011e330, 0x38, 0xc001b61700, 0x40, 0x40, 0x1)
2020-05-08T11:21:02.2638880Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:462
2020-05-08T11:21:02.2639460Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-05-08T11:21:02.2639810Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:360 +0x41c
2020-05-08T11:21:02.2640370Z FAIL	github.com/ethersphere/bee/pkg/file/splitter/internal	600.952s
```

**Comment by acud** [comment]
related to https://github.com/ethersphere/bee/issues/631
