### ISSUE TITLE
panic: runtime error: index out of range [2] with length 1

### ISSUE THREAD

**Issue by moremorefun** [ethersphere/bee#1893]
#### Summary
version: 85b3636
get panic by out of range when `github.com/ethersphere/bee/pkg/topology/pslice.(*PSlice).Add`

#### Steps to reproduce
Run for a short time

#### Expected behavior
no panic

#### Actual behavior
log
```
01:14:37 bee[191807]: time="2021-05-28T01:14:37Z" level=info msg="stream handler: successfully connected to peer 031ffe1df027c04d5cd5d5251117019aec07ca34ba57b6e56c8fee7bc5165d22 (inbound)"
01:14:37 bee[191807]: time="2021-05-28T01:14:37Z" level=warning msg="peer not reachable when attempting to connect"
01:14:39 bee[191807]: time="2021-05-28T01:14:39Z" level=warning msg="peer not reachable when attempting to connect"
01:14:39 bee[191807]: time="2021-05-28T01:14:39Z" level=info msg="greeting \"A Bunch of Bees are Bee Boxing 👊\" from peer: 7cdf438b112d8e42a03fdab42c781ab0c9b5c88d5d7624e1d065818d2eb571c9"
01:14:39 bee[191807]: time="2021-05-28T01:14:39Z" level=warning msg="peer not reachable when attempting to connect"
01:14:39 bee[191807]: time="2021-05-28T01:14:39Z" level=warning msg="could not send payment threshold announcement to peer 7debb2cb420e7f05638861d795675f4573482b06a29560af3f0474f426cdbba4"
01:14:39 bee[191807]: time="2021-05-28T01:14:39Z" level=warning msg="peer not reachable when attempting to connect"
01:14:39 bee[191807]: panic: runtime error: index out of range [2] with length 1
01:14:39 bee[191807]: goroutine 84111 [running]:
01:14:39 bee[191807]: github.com/ethersphere/bee/pkg/topology/pslice.(*PSlice).Add(0xc00057fbc0, 0xc00e3f1c90, 0x1, 0x1)
01:14:39 bee[191807]:         github.com/ethersphere/bee/pkg/topology/pslice/pslice.go:184 +0x6f5
01:14:39 bee[191807]: github.com/ethersphere/bee/pkg/topology/lightnode.(*Container).Connected(0xc001342ba0, 0x172d758, 0xc000359b80, 0xc009caeb20, 0x20, 0x20, 0x0)
01:14:39 bee[191807]:         github.com/ethersphere/bee/pkg/topology/lightnode/container.go:37 +0xc5
01:14:39 bee[191807]: github.com/ethersphere/bee/pkg/p2p/libp2p.New.func3(0x173e2f0, 0xc001414da0)
01:14:39 bee[191807]:         github.com/ethersphere/bee/pkg/p2p/libp2p/libp2p.go:337 +0x1042
01:14:39 bee[191807]: github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandlerMatch.func1(0xc0089df060, 0x20, 0x7fe6a677e7f8, 0xc001414da0, 0x1, 0x0)
01:14:39 bee[191807]:         github.com/libp2p/go-libp2p@v0.13.0/p2p/host/basic/basic_host.go:580 +0xa2
01:14:39 bee[191807]: created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
01:14:39 bee[191807]:         github.com/libp2p/go-libp2p@v0.13.0/p2p/host/basic/basic_host.go:416 +0x63a
```

**Comment by tomzhang** [comment]
same issue:
version info:
    bee version
**0.6.2-85b3636**

description:
  DEBU[2021-05-28T11:37:20+08:00] localstore pull subscription iteration: bin: 3, since: 1051, until: 1088: index iterator function: stop subscription
TRAC[2021-05-28T11:37:20+08:00] sending payment threshold announcement to peer ca6e3ab54b3882bd684cb5244b52489cf18da35a56d5b96c6e8c799acf7a40c7 of 10000000000000
panic: runtime error: index out of range [1] with length 1

goroutine 643828 [running]:
github.com/ethersphere/bee/pkg/topology/pslice.(*PSlice).Add(0xc00007fb60, 0xc00ecb9c90, 0x1, 0x1)
	github.com/ethersphere/bee/pkg/topology/pslice/pslice.go:184 +0x6f5
github.com/ethersphere/bee/pkg/topology/lightnode.(*Container).Connected(0xc0006b4480, 0x172d778, 0xc0001e8140, 0xc00b661260, 0x20, 0x20, 0x0)
	github.com/ethersphere/bee/pkg/topology/lightnode/container.go:37 +0xc5
github.com/ethersphere/bee/pkg/p2p/libp2p.New.func3(0x173e310, 0xc00cafdf40)
	github.com/ethersphere/bee/pkg/p2p/libp2p/libp2p.go:337 +0x1042
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandlerMatch.func1(0xc00c083b60, 0x20, 0x7f82c564f200, 0xc00cafdf40, 0x1, 0x0)
	github.com/libp2p/go-libp2p@v0.13.0/p2p/host/basic/basic_host.go:580 +0xa2
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
	github.com/libp2p/go-libp2p@v0.13.0/p2p/host/basic/basic_host.go:416 +0x63a
