### ISSUE TITLE
Panic on service restart, bee 0.6.2-984dca0a

### ISSUE THREAD

**Issue by tfalencar** [ethersphere/bee#2078]
#### Summary
I left bee running for a while, when I came back to check how everything is going, I noticed that: CPU usage is high, IO also high, however there was network traffic at all, it seems the bee is stuck.

#### Steps to reproduce
1- Run bee in "full mode" for several hours.
2- Bee stops exchanging network messages.
3- Restart the bee service with "systemctl restart bee", and the following panic was shown:

```
Jun 14 01:00:36 bee bee[4182]: time="2021-06-14T01:00:36+01:00" level=info msg="pull syncer shutting down"
Jun 14 01:00:37 bee bee[4182]: time="2021-06-14T01:00:37+01:00" level=warning msg="peer not reachable when attempting to connect"
Jun 14 01:00:37 bee bee[4182]: time="2021-06-14T01:00:37+01:00" level=warning msg="peer not reachable when attempting to connect"
Jun 14 01:00:38 bee bee[4182]: time="2021-06-14T01:00:38+01:00" level=warning msg="peer not reachable when attempting to connect"
Jun 14 01:00:38 bee bee[4182]: time="2021-06-14T01:00:38+01:00" level=warning msg="peer not reachable when attempting to connect"
Jun 14 01:00:38 bee bee[4182]: time="2021-06-14T01:00:38+01:00" level=warning msg="peer not reachable when attempting to connect"
Jun 14 01:00:38 bee bee[4182]: time="2021-06-14T01:00:38+01:00" level=warning msg="peer not reachable when attempting to connect"
Jun 14 01:00:46 bee bee[4182]: time="2021-06-14T01:00:46+01:00" level=warning msg="puller shutting down with running goroutines"
Jun 14 01:00:46 bee bee[4182]: time="2021-06-14T01:00:46+01:00" level=info msg="kademlia shutting down"
Jun 14 01:00:46 bee bee[4182]: time="2021-06-14T01:00:46+01:00" level=info msg="kademlia persisting peer metrics"
Jun 14 08:25:17 bee systemd[1]: Stopping Bee - Ethereum Swarm node...
Jun 14 08:25:17 bee bee[4182]: time="2021-06-14T08:25:17+01:00" level=info msg="shutting down"
Jun 14 08:25:17 bee bee[4182]: panic: close of closed channel
Jun 14 08:25:17 bee bee[4182]: goroutine 1705146413 [running]:
Jun 14 08:25:17 bee bee[4182]: github.com/ethersphere/bee/pkg/topology/kademlia.(*Kad).Halt(0x382e0b0)
Jun 14 08:25:17 bee bee[4182]:         github.com/ethersphere/bee/pkg/topology/kademlia/kademlia.go:1186 +0x20
Jun 14 08:25:17 bee bee[4182]: github.com/ethersphere/bee/pkg/node.(*Bee).Shutdown(0x314a1e0, 0x1150d10, 0x1305b340, 0x3, 0x1150d10)
Jun 14 08:25:17 bee bee[4182]:         github.com/ethersphere/bee/pkg/node/node.go:710 +0x3c
Jun 14 08:25:17 bee bee[4182]: github.com/ethersphere/bee/cmd/bee/cmd.(*command).initStartCmd.func1.2.1(0x17518600, 0x314a1e0, 0x11598d8, 0x3434180)
Jun 14 08:25:17 bee bee[4182]:         github.com/ethersphere/bee/cmd/bee/cmd/start.go:184 +0x94
Jun 14 08:25:17 bee bee[4182]: created by github.com/ethersphere/bee/cmd/bee/cmd.(*command).initStartCmd.func1.2
Jun 14 08:25:17 bee bee[4182]:         github.com/ethersphere/bee/cmd/bee/cmd/start.go:178 +0x78
Jun 14 08:25:17 bee systemd[1]: bee.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 14 08:25:17 bee systemd[1]: bee.service: Failed with result 'exit-code'.
Jun 14 08:25:17 bee systemd[1]: Stopped Bee - Ethereum Swarm node.
Jun 14 08:25:17 bee systemd[1]: Started Bee - Ethereum Swarm node.
Jun 14 08:25:18 bee bee[17804]: Welcome to the Swarm.... Bzzz Bzzzz Bzzzz#### Expected behavior
```

#### Expected behaviour

Bee runs stable.

#### Actual behavior

Bee doesn't operate normally and draws high CPU and IO.

This is a raspberry pi 4, armv7l GNU/Linux, with bee data on ext4 partition; Otherwise bee is running on a pretty standard configuration with default values; i.e., database capacity: 1000000 chunks, no special changes done there.

**Comment by CaWhi** [comment]
same problem，the bee just running a while，and it shutting down，no network traffic and high io，version is 0.6.2

**Comment by ldeffenb** [comment]
Look further back in the logs and I suspect you'll find an error monitoring the blockchain indicating an issue with your swap-endpoint.  0.6 monitors the swap-endpoint and will shut down your node if errors are detected.  The postage stamps require this in order to keep track of the currently valid stamps.  The most reliable swap-endpoint you can have is running your own local goerli node.

**Comment by tfalencar** [comment]
I guess it should still not panic though, right?

**Comment by ldeffenb** [comment]
> I guess it should still not panic though, right?

You are correct, but I suspect they'll also be asking you specifically what version of bee you are running.  Because I know there was an issue that has already been fixed that would cause a panic when multiple shutdowns were triggered.

**Comment by acud** [comment]
Should be fixed with the guard against duplicate shutdowns. Please reopen the issue in case the problem still persists
