### ISSUE TITLE
0.6.2 panic

### ISSUE THREAD

**Issue by amsandant** [ethersphere/bee#2150]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100 pc=0x473a65]

goroutine 116435349 [running]:
github.com/ethersphere/bee/pkg/pullsync/pullstorage.(*PullStorer).IntervalChunks.func1(0x1732178, 0xc008225300, 0x0, 0x0, 0x0, 0x0)
	github.com/ethersphere/bee/pkg/pullsync/pullstorage/pullstorage.go:97 +0x445
resenje.org/singleflight.(*Group).Do.func1(0xc0082252c0, 0x1732178, 0xc008225300, 0xc008225340)
	resenje.org/singleflight@v0.2.0/singleflight.go:59 +0x3e
created by resenje.org/singleflight.(*Group).Do
	resenje.org/singleflight@v0.2.0/singleflight.go:58 +0x2ed
```

**Comment by ldeffenb** [comment]
What exact "bee version" and executing on what platform?

**Comment by amsandant** [comment]
0.6.2-984dca0a  

Linux version 5.4.0-74-generic (buildd@lgw01-amd64-038) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04))

**Comment by acud** [comment]
this is very strange. do you have a bit more context for us? did this happen during shutdown? normal operation?
