### ISSUE TITLE
Splitter edge base exceeds work buffer

### ISSUE THREAD

**Issue by nolash** [ethersphere/bee#267]
# Task

With the given data passed as reader to the splitter, read is attempted past end of work buffer.

https://g33k.holbrook.no/53c5b791

Stack

```
ERRO[2020-06-07T18:36:19+02:00] http: panic serving [::1]:60176: runtime error: slice bounds out of range [:44894] with capacity 41040 
ERRO[2020-06-07T18:36:19+02:00] goroutine 24 [running]:                      
ERRO[2020-06-07T18:36:19+02:00] net/http.(*conn).serve.func1(0xc00018abe0)   
ERRO[2020-06-07T18:36:19+02:00] 	/usr/lib/go/src/net/http/server.go:1772 +0x139 
ERRO[2020-06-07T18:36:19+02:00] panic(0xf2eda0, 0xc001bfc200)                
ERRO[2020-06-07T18:36:19+02:00] 	/usr/lib/go/src/runtime/panic.go:975 +0x3e3 
ERRO[2020-06-07T18:36:19+02:00] github.com/ethersphere/bee/pkg/file/splitter/internal.(*SimpleSplitterJob).writeToLevel(0xc000234120, 0x0, 0xc001c10000, 0x1000, 0x1000, 0x1000, 0x1000) 
ERRO[2020-06-07T18:36:19+02:00] 	/home/lash/src/ext/swarm/bee/pkg/file/splitter/internal/job.go:106 +0x1d3 
ERRO[2020-06-07T18:36:19+02:00] github.com/ethersphere/bee/pkg/file/splitter/internal.(*SimpleSplitterJob).Write(0xc000234120, 0xc001c10000, 0x1000, 0x1000, 0x1000, 0x0, 0x0) 
ERRO[2020-06-07T18:36:19+02:00] 	/home/lash/src/ext/swarm/bee/pkg/file/splitter/internal/job.go:77 +0x80 
ERRO[2020-06-07T18:36:19+02:00] github.com/ethersphere/bee/pkg/file/splitter.(*simpleSplitter).Split(0xc0001171b0, 0x12603a0, 0xc0019439b0, 0x1255900, 0xc0019795c0, 0xed58, 0xc000369260, 0x2, 0x2, 0xc000369260, ...) 
ERRO[2020-06-07T18:36:19+02:00] 	/home/lash/src/ext/swarm/bee/pkg/file/splitter/splitter.go:56 +0x1be 
ERRO[2020-06-07T18:36:19+02:00] github.com/ethersphere/bee/pkg/api.(*server).rawUploadHandler(0xc00011f600, 0x125aae0, 0xc0019438f0, 0xc00026d000) 
ERRO[2020-06-07T18:36:19+02:00] 	/home/lash/src/ext/swarm/bee/pkg/api/raw.go:29 +0x1b0 
ERRO[2020-06-07T18:36:19+02:00] net/http.HandlerFunc.ServeHTTP(0xc00124f440, 0x125aae0, 0xc0019438f0, 0xc00026d000) 
```

## Acceptance criterea

Data which triggered edge case can be split without crashing.

**Comment by acud** [comment]
seems to be passing on current master:
```
growlie@growlie-strikes-back /tmp » wget https://g33k.holbrook.no/53c5b791                                                                                                                        [8/09/20| 3:17PM]
--2020-09-08 15:17:15--  https://g33k.holbrook.no/53c5b791
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving g33k.holbrook.no (g33k.holbrook.no)... 148.251.28.5
Connecting to g33k.holbrook.no (g33k.holbrook.no)|148.251.28.5|:443... connected.
HTTP request sent, awaiting response... 200 All yours data/53c5b791.txt 53c5b791
Length: 61392 (60K) [text/plain]
Saving to: ‘53c5b791’

53c5b791                                             100%[======================================================================================================================>]  59.95K  --.-KB/s    in 0.1s    

2020-09-08 15:17:18 (596 KB/s) - ‘53c5b791’ saved [61392/61392]

growlie@growlie-strikes-back /tmp »                                                                                                                                                               [8/09/20| 3:17PM]
growlie@growlie-strikes-back /tmp »                                                                                                                                                               [8/09/20| 3:23PM]
growlie@growlie-strikes-back /tmp »                                                                                                                                                               [8/09/20| 3:23PM]
growlie@growlie-strikes-back /tmp » cu                                                                                                                                                            [8/09/20| 3:23PM]
growlie@growlie-strikes-back /tmp » curl -X POST localhost:8080/files -F file=53c5b791 -v                                                                                                   130 ↵ [8/09/20| 3:23PM]
Note: Unnecessary use of -X or --request, POST is already inferred.                   
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> POST /files HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.72.0
> Accept: */*
> Content-Length: 147
> Content-Type: multipart/form-data; boundary=------------------------e25b9393bbd791fb
> 
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Expose-Headers: Swarm-Tag-Uid
< Content-Type: application/json; charset=utf-8
< Etag: "c0ca22e4ada0ef49a4b06588f17fb352340c9466656e84e1315f75b8c22afd6f"
< Swarm-Tag-Uid: 779744414
< Date: Tue, 08 Sep 2020 13:24:03 GMT
< Content-Length: 82
< 
{"reference":"c0ca22e4ada0ef49a4b06588f17fb352340c9466656e84e1315f75b8c22afd6f"}

* Connection #0 to host localhost left intact
growlie@growlie-strikes-back /tmp » curl -X POST localhost:8080/bytes -F file=53c5b791 -v                                                                                                         [8/09/20| 3:24PM]
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> POST /bytes HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.72.0
> Accept: */*
> Content-Length: 147
> Content-Type: multipart/form-data; boundary=------------------------8e1371813cbf247c
> 
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Expose-Headers: Swarm-Tag-Uid
< Content-Type: application/json; charset=utf-8
< Swarm-Tag-Uid: 2641436451
< Date: Tue, 08 Sep 2020 13:24:16 GMT
< Content-Length: 82
< 
{"reference":"9fcbb3c993bcf13dc5443c3f9180f39469b0321141fc0d7ffd051aacf55cff10"}

* Connection #0 to host localhost left intact
```
not sure if there's some other way to reproduce this. also, api endpoints have changed since this ticket was created.
