### ISSUE TITLE
ultra-light mode crashes

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#3082]
### Context
bee version 1.6.2-09106b54
installed by swarm-desktop 0.15.1

### Summary
While fetching my very large OSM dataset, the ultra-light mode bee crashes with:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x144c66a]

goroutine 9725 [running]:
github.com/ethersphere/bee/pkg/postage.ValidStamp.func1({0x2223858, 0xc0041b2730}, {0xc0031dfd00, 0x71, 0x71})
	github.com/ethersphere/bee/pkg/postage/stamp.go:133 +0x28a
github.com/ethersphere/bee/pkg/netstore.(*store).put.func1()
	github.com/ethersphere/bee/pkg/netstore/netstore.go:123 +0x363
created by github.com/ethersphere/bee/pkg/netstore.(*store).put
	github.com/ethersphere/bee/pkg/netstore/netstore.go:99 +0xa7
```

### Expected behavior
I should be able to retrieve anything from the swarm, right?

### Actual behavior
Repeated crashes as I continued to attempt to retrieve chunks as soon as the bee node was restarted by swarm-desktop.

### Steps to reproduce
Fetch lots and lots of chunks via a swarm-desktop, ultra-light bee node.

I'm using a modified pin-reference.ts script from github.com/ldeffenb/Swarming-Wikipedia

The modification is that I'm not doing pinning by inserting a return at the beginning of the pinReference function.   My command line is:
```
node --max-old-space-size=65536 dist/pin-reference.js f09da1184cc9ef6af3b228f72c6ff965fcfee58b47d65d52ef6cf4e5347c766e http://localhost:1633 http://192.168.10.123:11633 >ultraLight-0.out
```
Where http://localhost:1633 is the local ultra-light swarm-desktop bee node and http://192.168.10.123:11633 is my original uploading node that will be used to -X PUT /stewardship if any chunks are non-retrievable.  You can invoke the script without that final argument and it will skip any /stewardship recovery attempts.

### Possible solution
The root cause is that ultra-light nodes are running without the chainEnabled causing node to create and use a NoOpBatchStore to create the postage stamp ValidStampFn.  But when NoOpBatchStore.Get() is invoked by ValidStampFn on behalf of the netstore.put(), NoOpBatchStore.Get() returns nil,nil which indicates no error but also doesn't return a stamp batch causing the "nil pointer dereference" when b==nil.

It looks like if NoOpBatchStore.Get() would return an error, then this particular code path would no longer crash.  If that error is storage.ErrNotFound, then it will be logged by ValidStampFn and returned.  But when an error gets back to the netstore it will force the chunk into the cache only and prevent it from pinning into the reserve.  Returning any error except storage.ErrNotFound will remove the unnecessary log while still preventing the chunk from pinning.  At least, that's the behavior in the 1.6.2 tagged source.

Read my full traceback at https://github.com/ethersphere/bee/issues/3082#issuecomment-1179286794

**Comment by ldeffenb** [comment]
Looking at my logs more closely shows that the failing chunk (1c4bfe6.....032b9) is the data contents of a PNG file within the manifest.  You should be able to access the same file via
/bzz/f09da1184cc9ef6af3b228f72c6ff965fcfee58b47d65d52ef6cf4e5347c766e/0/coverage.png
The following URL pasted into a local browser on the ultra-light node's machine also kills the bee node with the same stack dump.
```
http://localhost:1633/bzz/f09da1184cc9ef6af3b228f72c6ff965fcfee58b47d65d52ef6cf4e5347c766e/0/coverage.png
```
Interestingly, the following link works which may indicate that this is a new bust in 1.6.2 with no longer caching invalid stamp chunks?  Especially if the bzz.link gateways have not been updated.  (Even though this chunk should NOT have an invalid stamp on it...)
```
https://bzz.link/bzz/f09da1184cc9ef6af3b228f72c6ff965fcfee58b47d65d52ef6cf4e5347c766e/0/coverage.png
```

**Comment by ldeffenb** [comment]
This is definitely an issue with any node that does not have the chain enabled.  The node is dying in the ValidStampFn when invoked by netstore https://github.com/ethersphere/bee/blob/09106b54b4577a0953b4ee63cab8f73ed24e71e0/pkg/netstore/netstore.go#L123

This ValidStampFn was passed in from node.go when the netstore instance was created https://github.com/ethersphere/bee/blob/09106b54b4577a0953b4ee63cab8f73ed24e71e0/pkg/node/node.go#L803

This validStamp was created by Postage which was passed in a batchStore https://github.com/ethersphere/bee/blob/09106b54b4577a0953b4ee63cab8f73ed24e71e0/pkg/node/node.go#L598

Postage's ValidStamp routine is going to invoke batchStore.Get to retrieve stamp batch information.  It is expecting to get an error or a stamp batch (b) to check https://github.com/ethersphere/bee/blob/09106b54b4577a0953b4ee63cab8f73ed24e71e0/pkg/postage/stamp.go#L119

However, the batchStore that set up the ValidStamp is actually an instance of NoOpBatchStore for any node running without the chainEnabled (like an ultra-light swarm-desktop node)  https://github.com/ethersphere/bee/blob/09106b54b4577a0953b4ee63cab8f73ed24e71e0/pkg/node/node.go#L258

And the crux of the problem is that NoOpBatchStore's Get() method returns nil,nil indicating no error, but also not returning a stamp batch to check causing the crash in the ValidStampFn.  https://github.com/ethersphere/bee/blob/09106b54b4577a0953b4ee63cab8f73ed24e71e0/pkg/postage/noop.go#L14

So, greater minds than mine need to determine how to actually FIX this, but the root cause is a Get() method that is lying about a successful invocation (err=nil).
