### ISSUE TITLE
Test timing out `TestReserveSamplerStop`

### ISSUE THREAD

**Issue by vladopajic** [ethersphere/bee#3636]
```
=== RUN   TestReserveSamplerStop
panic: test timed out after 10m0s

goroutine 2024726 [running]:
testing.(*M).startAlarm.func1()
	/Users/runner/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1788 +0xbb
created by time.goFunc
	/Users/runner/hostedtoolcache/go/1.17.13/x64/src/time/sleep.go:180 +0x4a

goroutine 1 [chan receive, 1 minutes]:
testing.(*T).Run(0xc0000824e0, {0x49b420e, 0x16}, 0x4af6650)
	/Users/runner/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1307 +0x752
testing.runTests.func1(0x0)
	/Users/runner/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1598 +0x9a
testing.tRunner(0xc0000824e0, 0xc000153bf8)
	/Users/runner/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1259 +0x230
testing.runTests(0xc000214080, {0x502fb60, 0x4b, 0x4b}, {0x0, 0xc00023e680, 0x503cb20})
	/Users/runner/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1596 +0x7cb
testing.(*M).Run(0xc000214080)
	/Users/runner/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1504 +0x9d2
main.main()
	_testmain.go:197 +0x22c

goroutine 1561173 [select, 1 minutes]:
github.com/ethersphere/bee/pkg/sharky.(*shard).process(0xc000c28280)
	/Users/runner/work/bee/bee/pkg/sharky/shard.go:110 +0x2ec
github.com/ethersphere/bee/pkg/sharky.(*Store).create.func1()
	/Users/runner/work/bee/bee/pkg/sharky/store.go:106 +0xb8
created by github.com/ethersphere/bee/pkg/sharky.(*Store).create
	/Users/runner/work/bee/bee/pkg/sharky/store.go:104 +0x6ec

goroutine 1561219 [select, 1 minutes]:
github.com/ethersphere/bee/pkg/sharky.(*shard).process(0xc000c28a00)
	/Users/runner/work/bee/bee/pkg/sharky/store.go:112 +0xd3
created by github.com/ethersphere/bee/pkg/sharky.(*Store).create
	/Users/runner/work/bee/bee/pkg/sharky/store.go:110 +0x825

goroutine 1561197 [select, 1 minutes]:
github.com/ethersphere/bee/pkg/sharky.(*shard).process(0xc000c28690)
	/Users/runner/work/bee/bee/pkg/sharky/shard.go:110 +0x2ec
github.com/ethersphere/bee/pkg/sharky.(*Store).create.func1()
	/Users/runner/work/bee/bee/pkg/sharky/store.go:106 +0xb8
created by github.com/ethersphere/bee/pkg/sharky.(*Store).create
	/Users/runner/work/bee/bee/pkg/sharky/store.go:104 +0x6ec

goroutine 1561169 [select, 1 minutes]:
github.com/ethersphere/bee/pkg/sharky.(*shard).process(0xc000c281e0)
	/Users/runner/work/bee/bee/pkg/sharky/shard.go:110 +0x2ec
github.com/ethersphere/bee/pkg/sharky.(*Store).create.func1()
	/Users/runner/work/bee/bee/pkg/sharky/store.go:106 +0xb8
created by github.com/ethersphere/bee/pkg/sharky.(*Store).create
	/Users/runner/work/bee/bee/pkg/sharky/store.go:104 +0x6ec

goroutine 1561183 [select, 1 minutes]:
github.com/ethersphere/bee/pkg/sharky.(*shard).process(0xc000c28460)
	/Users/runner/work/bee/bee/pkg/sharky/shard.go:110 +0x2ec
github.com/ethersphere/bee/pkg/sharky.(*Store).create.func1()
	/Users/runner/work/bee/bee/pkg/sharky/store.go:106 +0xb8
created by github.com/ethersphere/bee/pkg/sharky.(*Store).create
	/Users/runner/work/bee/bee/pkg/sharky/store.go:104 +0x6ec

goroutine 1561207 [select, 1 minutes]:
github.com/ethersphere/bee/pkg/sharky.(*shard).process(0xc000c28820)
	/Users/runner/work/bee/bee/pkg/sharky/shard.go:110 +0x2ec
github.com/ethersphere/bee/pkg/sharky.(*Store).create.func1()
	/Users/runner/work/bee/bee/pkg/sharky/store.go:106 +0xb8
created by github.com/ethersphere/bee/pkg/sharky.(*Store).create
	/Users/runner/work/bee/bee/pkg/sharky/store.go:104 +0x6ec

goroutine 1561217 [select, 1 minutes]:
github.com/ethersphere/bee/pkg/sharky.(*shard).process(0xc000c289b0)
	/Users/runner/work/bee/bee/pkg/sharky/shard.go:110 +0x2ec
github.com/ethersphere/bee/pkg/sharky.(*Store).create.func1()
	/Users/runner/work/bee/bee/pkg/sharky/store.go:106 +0xb8
created by github.com/ethersphere/bee/pkg/sharky.(*Store).create
	/Users/runner/work/bee/bee/pkg/sharky/store.go:104 +0x6ec

goroutine 1561175 [select, 1 minutes]:
github.com/ethersphere/bee/pkg/sharky.(*shard).process(0xc000c282d0)
	/Users/runner/work/bee/bee/pkg/sharky/shard.go:110 +0x2ec
github.com/ethersphere/bee/pkg/sharky.(*Store).create.func1()
	/Users/runner/work/bee/bee/pkg/sharky/store.go:106 +0xb8
created by github.com/ethersphere/bee/pkg/sharky.(*Store).create
	/Users/runner/work/bee/bee/pkg/sharky/store.go:104 +0x6ec

goroutine 2024679 [runnable]:
github.com/ethersphere/bee/pkg/bmt.doHash({0x4bd35b8, 0xc00029e8c0}, {0xc000a55688, 0x2, 0x2})
	/Users/runner/work/bee/bee/pkg/bmt/bmt.go:272 +0x145
github.com/ethersphere/bee/pkg/bmt.(*Hasher).writeNode(0xc00056c910, 0xc000293ec0, 0x0, {0xc0009c2020, 0x20, 0x20})
	/Users/runner/work/bee/bee/pkg/bmt/bmt.go:186 +0x299
github.com/ethersphere/bee/pkg/bmt.(*Hasher).processSection(0xc00056c910, 0x11, 0x0)
	/Users/runner/work/bee/bee/pkg/bmt/bmt.go:156 +0x29f
created by github.com/ethersphere/bee/pkg/bmt.(*Hasher).Write
	/Users/runner/work/bee/bee/pkg/bmt/bmt.go:119 +0x2de

goroutine 1561221 [select, 1 minutes]:
github.com/ethersphere/bee/pkg/localstore.(*DB).collectGarbageWorker(0xc000d7d000)
	/Users/runner/work/bee/bee/pkg/localstore/gc.go:55 +0x189
created by github.com/ethersphere/bee/pkg/localstore.New
	/Users/runner/work/bee/bee/pkg/localstore/localstore.go:646 +0x39ec

goroutine 1561153 [select, 1 minutes]:
github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0xc001168000)
	/Users/runner/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session_util.go:189 +0x79d
created by github.com/syndtr/goleveldb/leveldb.newSession
	/Users/runner/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session.go:93 +0x566

goroutine 1561203 [select, 1 minutes]:
github.com/ethersphere/bee/pkg/sharky.(*shard).process(0xc000c28780)
	/Users/runner/work/bee/bee/pkg/sharky/shard.go:110 +0x2ec
github.com/ethersphere/bee/pkg/sharky.(*Store).create.func1()
	/Users/runner/work/bee/bee/pkg/sharky/store.go:106 +0xb8
created by github.com/ethersphere/bee/pkg/sharky.(*Store).create
	/Users/runner/work/bee/bee/pkg/sharky/store.go:104 +0x6ec
FAIL	github.com/ethersphere/bee/pkg/localstore	600.539s
```

**Comment by vladopajic** [comment]
It looks like tests timed out on this test, not because of it.
