### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference error

### ISSUE THREAD

**Issue by diglos** [ethersphere/bee#3886]
### Context
Version: 1.13.0-f1067884 / ARM64 Rock 5B board / Linux Ubuntu server 20.04

Clients params:

clef-signer-endpoint: /var/lib/bee-clef/clef.ipc
data-dir: /home/ethereum/.bee
password-file: /etc/ethereum/jwtsecret
swap-endpoint: https://rpc.gnosischain.com

### Summary
After funding the address with XDAI I'm getting a SIGSEV

### Expected behavior
Client normal start

### Actual behavior

Client crashes with a runtime error:

```
Mar 15 08:53:36 ethereumonarm-rock5b-c7ace1fe6 bee[60603]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 15 08:53:36 ethereumonarm-rock5b-c7ace1fe6 bee[60603]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xf0 pc=0xc0b880]
Mar 15 08:53:36 ethereumonarm-rock5b-c7ace1fe6 bee[60603]: goroutine 50 [running]:
Mar 15 08:53:36 ethereumonarm-rock5b-c7ace1fe6 bee[60603]: github.com/ethersphere/bee/pkg/api.(*Service).MetricsRegistry(...)
Mar 15 08:53:36 ethereumonarm-rock5b-c7ace1fe6 bee[60603]:         github.com/ethersphere/bee/pkg/api/metrics.go:164
Mar 15 08:53:36 ethereumonarm-rock5b-c7ace1fe6 bee[60603]: github.com/ethersphere/bee/pkg/node.NewBee({0x1532668, 0x400007ea00}, {0xfaebac, 0x5}, 0x4003b04060, {0x1534c40?, 0x400020c000}, 0x1, {0x153d9e8, 0x400007e9b0}, ...)
Mar 15 08:53:36 ethereumonarm-rock5b-c7ace1fe6 bee[60603]:         github.com/ethersphere/bee/pkg/node/node.go:594 +0x2760
Mar 15 08:53:36 ethereumonarm-rock5b-c7ace1fe6 bee[60603]: github.com/ethersphere/bee/cmd/bee/cmd.buildBeeNode({0x1532668, 0x400007ea00}, 0x400007e870, 0x4000139b80?, {0x153d9e8, 0x400007e9b0})
Mar 15 08:53:36 ethereumonarm-rock5b-c7ace1fe6 bee[60603]:         github.com/ethersphere/bee/cmd/bee/cmd/start.go:295 +0xf14
Mar 15 08:53:36 ethereumonarm-rock5b-c7ace1fe6 bee[60603]: github.com/ethersphere/bee/cmd/bee/cmd.buildBeeNodeAsync.func1()
Mar 15 08:53:36 ethereumonarm-rock5b-c7ace1fe6 bee[60603]:         github.com/ethersphere/bee/cmd/bee/cmd/start.go:200 +0x3c
Mar 15 08:53:36 ethereumonarm-rock5b-c7ace1fe6 bee[60603]: created by github.com/ethersphere/bee/cmd/bee/cmd.buildBeeNodeAsync
Mar 15 08:53:36 ethereumonarm-rock5b-c7ace1fe6 bee[60603]:         github.com/ethersphere/bee/cmd/bee/cmd/start.go:199 +0xfc
```

### Steps to reproduce
The client is crosscompiled but we tried native compilation as well. Start the client with the above params.

**Comment by Cafe137** [comment]
Reproducible with `1.13.0` and `1.13.1-rc1` on MacOS ARM64

```
"time"="2023-03-16 14:41:08.541135" "level"="info" "logger"="node" "msg"="bee version" "version"="1.13.1-rc1-7780675d"
"time"="2023-03-16 14:41:08.541422" "level"="warning" "logger"="node" "msg"="clef is not enabled; portability and security of your keys is sub optimal"
"time"="2023-03-16 14:41:08.619989" "level"="info" "logger"="node" "msg"="swarm public key" "public_key"="xxx"
"time"="2023-03-16 14:41:08.733667" "level"="info" "logger"="node" "msg"="pss public key" "public_key"="xxx"
"time"="2023-03-16 14:41:08.733685" "level"="info" "logger"="node" "msg"="using ethereum address" "address"="xxx"
"time"="2023-03-16 14:41:08.812148" "level"="info" "logger"="node" "msg"="using overlay address" "address"="xxx"
"time"="2023-03-16 14:41:08.812170" "level"="info" "logger"="node" "msg"="starting with an enabled chain backend"
"time"="2023-03-16 14:41:08.970734" "level"="info" "logger"="node" "msg"="connected to ethereum backend" "version"="Nethermind/v1.17.2+4faa7314/linux-x64/dotnet7.0.4"
"time"="2023-03-16 14:41:09.004276" "level"="info" "logger"="node" "msg"="using chain with network network" "chain_id"=100 "network_id"=1
"time"="2023-03-16 14:41:09.072666" "level"="info" "logger"="node" "msg"="using default factory address" "chain_id"=100 "factory_address"="0xC2d5A532cf69AA9A1378737D8ccDEF884B6E7420"
"time"="2023-03-16 14:41:09.193705" "level"="info" "logger"="node/chequebook" "msg"="using existing chequebook" "chequebook_address"="xxx"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0xf0 pc=0x1011ff770]

goroutine 29 [running]:
github.com/ethersphere/bee/pkg/api.(*Service).MetricsRegistry(...)
	github.com/ethersphere/bee/pkg/api/metrics.go:164
github.com/ethersphere/bee/pkg/node.NewBee({0x101b2bd18, 0x14000f54b90}, {0x140004e97e8, 0x5}, 0x14004084060, {0x101b2e180?, 0x1400000e078}, 0x1, {0x101b36f08, 0x14000f54b40}, ...)
	github.com/ethersphere/bee/pkg/node/node.go:592 +0x2760
github.com/ethersphere/bee/cmd/bee/cmd.buildBeeNode({0x101b2bd18, 0x14000f54b90}, 0x14000f54a50, 0x14000283b80?, {0x101b36f08, 0x14000f54b40})
	github.com/ethersphere/bee/cmd/bee/cmd/start.go:295 +0xf14
github.com/ethersphere/bee/cmd/bee/cmd.buildBeeNodeAsync.func1()
	github.com/ethersphere/bee/cmd/bee/cmd/start.go:200 +0x3c
created by github.com/ethersphere/bee/cmd/bee/cmd.buildBeeNodeAsync
	github.com/ethersphere/bee/cmd/bee/cmd/start.go:199 +0xfc
```
