### ISSUE TITLE
TestSplitThenJoin hangs

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#392]
```
2020-06-26T14:18:12.5604960Z === RUN   TestSplitThenJoin
2020-06-26T14:18:12.5999580Z === RUN   TestSplitThenJoin/0
2020-06-26T14:18:12.6048800Z === RUN   TestSplitThenJoin/1
2020-06-26T14:18:12.6379760Z === RUN   TestSplitThenJoin/2
2020-06-26T14:18:12.6607320Z === RUN   TestSplitThenJoin/3
2020-06-26T14:18:12.6608280Z === RUN   TestSplitThenJoin/4
2020-06-26T14:18:12.7617170Z === RUN   TestSplitThenJoin/5
2020-06-26T14:18:12.7644700Z === RUN   TestSplitThenJoin/6
2020-06-26T14:18:12.7785950Z === RUN   TestSplitThenJoin/7
2020-06-26T14:18:12.7951410Z === RUN   TestSplitThenJoin/8
2020-06-26T14:18:12.7952150Z === RUN   TestSplitThenJoin/9
2020-06-26T14:18:12.8029010Z === RUN   TestSplitThenJoin/10
2020-06-26T14:18:12.8124640Z === RUN   TestSplitThenJoin/11
2020-06-26T14:18:12.8226710Z === RUN   TestSplitThenJoin/12
2020-06-26T14:18:12.8283110Z === RUN   TestSplitThenJoin/13
2020-06-26T14:18:12.8314900Z === RUN   TestSplitThenJoin/14
2020-06-26T14:18:12.8342300Z === RUN   TestSplitThenJoin/15
2020-06-26T14:18:12.8424310Z === RUN   TestSplitThenJoin/16
2020-06-26T14:18:12.8495280Z === RUN   TestSplitThenJoin/17
2020-06-26T14:18:12.8545380Z === RUN   TestSplitThenJoin/18
2020-06-26T14:18:12.8565990Z === RUN   TestSplitThenJoin/19
2020-06-26T14:18:12.8614830Z === RUN   TestSplitThenJoin/20
2020-06-26T14:18:12.8655790Z panic: test timed out after 10m0s
2020-06-26T14:18:12.8757070Z 
2020-06-26T14:18:12.8858630Z goroutine 2058728 [running]:
2020-06-26T14:18:12.8958920Z testing.(*M).startAlarm.func1()
2020-06-26T14:18:12.9064080Z 	/Users/runner/hostedtoolcache/go/1.14.4/x64/src/testing/testing.go:1459 +0x11c
2020-06-26T14:18:12.9163100Z created by time.goFunc
2020-06-26T14:18:12.9194930Z 	/Users/runner/hostedtoolcache/go/1.14.4/x64/src/time/sleep.go:168 +0x52
2020-06-26T14:18:12.9228380Z 
2020-06-26T14:18:12.9275100Z goroutine 1 [chan receive, 9 minutes]:
2020-06-26T14:18:12.9375550Z testing.(*T).Run(0xc000232120, 0x1727eb1, 0x11, 0x17420b0, 0x1)
2020-06-26T14:18:12.9424890Z 	/Users/runner/hostedtoolcache/go/1.14.4/x64/src/testing/testing.go:1043 +0x699
2020-06-26T14:18:12.9467050Z testing.runTests.func1(0xc000232120)
2020-06-26T14:18:12.9488910Z 	/Users/runner/hostedtoolcache/go/1.14.4/x64/src/testing/testing.go:1284 +0xa7
2020-06-26T14:18:12.9515160Z testing.tRunner(0xc000232120, 0xc0000bfd50)
2020-06-26T14:18:12.9522670Z 	/Users/runner/hostedtoolcache/go/1.14.4/x64/src/testing/testing.go:991 +0x1ec
2020-06-26T14:18:12.9524560Z testing.runTests(0xc000212380, 0x1b6e3e0, 0x3, 0x3, 0x0)
2020-06-26T14:18:12.9539160Z 	/Users/runner/hostedtoolcache/go/1.14.4/x64/src/testing/testing.go:1282 +0x528
2020-06-26T14:18:12.9540260Z testing.(*M).Run(0xc000262000, 0x0)
2020-06-26T14:18:12.9545270Z 	/Users/runner/hostedtoolcache/go/1.14.4/x64/src/testing/testing.go:1199 +0x300
2020-06-26T14:18:12.9548260Z main.main()
2020-06-26T14:18:12.9549590Z 	_testmain.go:50 +0x224
2020-06-26T14:18:12.9549790Z 
2020-06-26T14:18:12.9550130Z goroutine 47 [chan receive, 3 minutes]:
2020-06-26T14:18:12.9550440Z testing.(*T).Run(0xc0001366c0, 0x173c7dc, 0x2, 0x17420c8, 0x1)
2020-06-26T14:18:12.9550780Z 	/Users/runner/hostedtoolcache/go/1.14.4/x64/src/testing/testing.go:1043 +0x699
2020-06-26T14:18:12.9553670Z github.com/ethersphere/bee/pkg/file_test.TestSplitThenJoin(0xc0001366c0)
2020-06-26T14:18:12.9554450Z 	/Users/runner/runners/2.263.0/work/bee/bee/pkg/file/file_test.go:38 +0x89
2020-06-26T14:18:12.9555120Z testing.tRunner(0xc0001366c0, 0x17420b0)
2020-06-26T14:18:12.9555740Z 	/Users/runner/hostedtoolcache/go/1.14.4/x64/src/testing/testing.go:991 +0x1ec
2020-06-26T14:18:12.9562310Z created by testing.(*T).Run
2020-06-26T14:18:12.9563090Z 	/Users/runner/hostedtoolcache/go/1.14.4/x64/src/testing/testing.go:1042 +0x661
2020-06-26T14:18:12.9563580Z 
2020-06-26T14:18:12.9564210Z goroutine 2059001 [runnable]:
2020-06-26T14:18:12.9564670Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc00009d230, 0x3c, 0xc006b16fc0, 0x40, 0x40, 0x1)
2020-06-26T14:18:12.9564950Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:462
2020-06-26T14:18:12.9568920Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-06-26T14:18:12.9569280Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:360 +0x41c
2020-06-26T14:18:12.9569370Z 
2020-06-26T14:18:12.9569560Z goroutine 2058993 [runnable]:
2020-06-26T14:18:12.9569960Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc00009d230, 0x34, 0xc006b16dc0, 0x40, 0x40, 0x1)
2020-06-26T14:18:12.9570950Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:462
2020-06-26T14:18:12.9571220Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-06-26T14:18:12.9571510Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:360 +0x41c
2020-06-26T14:18:12.9571640Z 
2020-06-26T14:18:12.9571950Z goroutine 2058995 [runnable]:
2020-06-26T14:18:12.9572350Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc00009d230, 0x36, 0xc006b16e40, 0x40, 0x40, 0x1)
2020-06-26T14:18:12.9572650Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:462
2020-06-26T14:18:12.9572950Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-06-26T14:18:12.9573280Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:360 +0x41c
2020-06-26T14:18:12.9573370Z 
2020-06-26T14:18:12.9573570Z goroutine 2059000 [runnable]:
2020-06-26T14:18:12.9573870Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc00009d230, 0x3b, 0xc006b16f80, 0x40, 0x40, 0x1)
2020-06-26T14:18:12.9574240Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:462
2020-06-26T14:18:12.9574570Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-06-26T14:18:12.9574890Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:360 +0x41c
2020-06-26T14:18:12.9575030Z 
2020-06-26T14:18:12.9575220Z goroutine 1124289 [runnable]:
2020-06-26T14:18:12.9575570Z github.com/ethersphere/bmt/legacy.(*Hasher).write(0xc00009d230, 0xc004d314c0, 0x1000, 0x10bd0, 0xc0001a5f08)
2020-06-26T14:18:12.9575900Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:362 +0x43b
2020-06-26T14:18:12.9576260Z github.com/ethersphere/bmt/legacy.(*Hasher).Write(0xc00009d230, 0xc004d314c0, 0x1000, 0x10bd0, 0xc0001181c0, 0x1, 0x1)
2020-06-26T14:18:12.9576860Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:321 +0x57
2020-06-26T14:18:12.9577260Z github.com/ethersphere/bee/pkg/file/splitter/internal.(*SimpleSplitterJob).sumLevel(0xc0004fa120, 0x0, 0x10bd0, 0xc004d2d000, 0x1000, 0x1000, 0x1)
2020-06-26T14:18:12.9578020Z 	/Users/runner/runners/2.263.0/work/bee/bee/pkg/file/splitter/internal/job.go:138 +0x4df
2020-06-26T14:18:12.9578850Z github.com/ethersphere/bee/pkg/file/splitter/internal.(*SimpleSplitterJob).writeToLevel(0xc0004fa120, 0x0, 0xc004d2d000, 0x1000, 0x1000, 0x1000, 0x0)
2020-06-26T14:18:12.9579430Z 	/Users/runner/runners/2.263.0/work/bee/bee/pkg/file/splitter/internal/job.go:109 +0x311
2020-06-26T14:18:12.9579800Z github.com/ethersphere/bee/pkg/file/splitter/internal.(*SimpleSplitterJob).Write(0xc0004fa120, 0xc004d2d000, 0x1000, 0x1000, 0x1000, 0x0, 0x0)
2020-06-26T14:18:12.9580080Z 	/Users/runner/runners/2.263.0/work/bee/bee/pkg/file/splitter/internal/job.go:77 +0x1cf
2020-06-26T14:18:12.9580470Z github.com/ethersphere/bee/pkg/file/splitter.(*simpleSplitter).Split(0xc000214420, 0x17e5ec0, 0xc004ce10c0, 0x17e0f40, 0xc0000b21a0, 0x4000020, 0x20, 0x40, 0x2, 0x0, ...)
2020-06-26T14:18:12.9580760Z 	/Users/runner/runners/2.263.0/work/bee/bee/pkg/file/splitter/splitter.go:56 +0x19a
2020-06-26T14:18:12.9581260Z github.com/ethersphere/bee/pkg/file_test.testSplitThenJoin(0xc000136000)
2020-06-26T14:18:12.9581620Z 	/Users/runner/runners/2.263.0/work/bee/bee/pkg/file/file_test.go:56 +0x412
2020-06-26T14:18:12.9581920Z testing.tRunner(0xc000136000, 0x17420c8)
2020-06-26T14:18:12.9582260Z 	/Users/runner/hostedtoolcache/go/1.14.4/x64/src/testing/testing.go:991 +0x1ec
2020-06-26T14:18:12.9582470Z created by testing.(*T).Run
2020-06-26T14:18:12.9582720Z 	/Users/runner/hostedtoolcache/go/1.14.4/x64/src/testing/testing.go:1042 +0x661
2020-06-26T14:18:12.9582920Z 
2020-06-26T14:18:12.9583080Z goroutine 2058999 [runnable]:
2020-06-26T14:18:12.9583470Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc00009d230, 0x3a, 0xc006b16f40, 0x40, 0x40, 0x1)
2020-06-26T14:18:12.9583750Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:462
2020-06-26T14:18:12.9584000Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-06-26T14:18:12.9584680Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:360 +0x41c
2020-06-26T14:18:12.9584960Z 
2020-06-26T14:18:12.9585370Z goroutine 2058969 [runnable]:
2020-06-26T14:18:12.9585680Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc00009d230, 0x1c, 0xc006b16780, 0x40, 0x40, 0x1)
2020-06-26T14:18:12.9585950Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:462
2020-06-26T14:18:12.9586150Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-06-26T14:18:12.9586420Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:360 +0x41c
2020-06-26T14:18:12.9586500Z 
2020-06-26T14:18:12.9586680Z goroutine 2058994 [runnable]:
2020-06-26T14:18:12.9586980Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc00009d230, 0x35, 0xc006b16e00, 0x40, 0x40, 0x1)
2020-06-26T14:18:12.9587250Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:462
2020-06-26T14:18:12.9587570Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-06-26T14:18:12.9587910Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:360 +0x41c
2020-06-26T14:18:12.9588540Z 
2020-06-26T14:18:12.9588770Z goroutine 2058968 [runnable]:
2020-06-26T14:18:12.9589090Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc00009d230, 0x1b, 0xc006b16740, 0x40, 0x40, 0x1)
2020-06-26T14:18:12.9589380Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:462
2020-06-26T14:18:12.9589620Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-06-26T14:18:12.9589850Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:360 +0x41c
2020-06-26T14:18:12.9589930Z 
2020-06-26T14:18:12.9590100Z goroutine 2058998 [runnable]:
2020-06-26T14:18:12.9590360Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc00009d230, 0x39, 0xc006b16f00, 0x40, 0x40, 0x1)
2020-06-26T14:18:12.9590980Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:462
2020-06-26T14:18:12.9591270Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-06-26T14:18:12.9591530Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:360 +0x41c
2020-06-26T14:18:12.9591640Z 
2020-06-26T14:18:12.9591820Z goroutine 2058997 [runnable]:
2020-06-26T14:18:12.9592390Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc00009d230, 0x38, 0xc006b16ec0, 0x40, 0x40, 0x1)
2020-06-26T14:18:12.9592680Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:462
2020-06-26T14:18:12.9592920Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-06-26T14:18:12.9593190Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:360 +0x41c
2020-06-26T14:18:12.9593260Z 
2020-06-26T14:18:12.9593410Z goroutine 2058996 [runnable]:
2020-06-26T14:18:12.9593670Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc00009d230, 0x37, 0xc006b16e80, 0x40, 0x40, 0x1)
2020-06-26T14:18:12.9593910Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:462
2020-06-26T14:18:12.9594150Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-06-26T14:18:12.9594740Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.1/legacy/bmt.go:360 +0x41c
2020-06-26T14:18:12.9594990Z FAIL	github.com/ethersphere/bee/pkg/file	600.705s
```

**Comment by acud** [comment]
another one from yesterday:
```
2020-07-27T13:39:58.1569660Z === RUN   TestSplitThenJoin
2020-07-27T13:39:58.1603830Z === RUN   TestSplitThenJoin/0
2020-07-27T13:39:58.1703740Z === RUN   TestSplitThenJoin/1
2020-07-27T13:39:58.1733370Z === RUN   TestSplitThenJoin/2
2020-07-27T13:39:58.1740340Z === RUN   TestSplitThenJoin/3
2020-07-27T13:39:58.1845580Z === RUN   TestSplitThenJoin/4
2020-07-27T13:39:58.1849340Z === RUN   TestSplitThenJoin/5
2020-07-27T13:39:58.1854880Z === RUN   TestSplitThenJoin/6
2020-07-27T13:39:58.1883860Z === RUN   TestSplitThenJoin/7
2020-07-27T13:39:58.1986820Z === RUN   TestSplitThenJoin/8
2020-07-27T13:39:58.2089780Z === RUN   TestSplitThenJoin/9
2020-07-27T13:39:58.2201580Z === RUN   TestSplitThenJoin/10
2020-07-27T13:39:58.2282040Z === RUN   TestSplitThenJoin/11
2020-07-27T13:39:58.2385350Z === RUN   TestSplitThenJoin/12
2020-07-27T13:39:58.2449760Z === RUN   TestSplitThenJoin/13
2020-07-27T13:39:58.2482070Z === RUN   TestSplitThenJoin/14
2020-07-27T13:39:58.2528990Z === RUN   TestSplitThenJoin/15
2020-07-27T13:39:58.2549130Z === RUN   TestSplitThenJoin/16
2020-07-27T13:39:58.2574850Z === RUN   TestSplitThenJoin/17
2020-07-27T13:39:58.2591300Z === RUN   TestSplitThenJoin/18
2020-07-27T13:39:58.2602290Z === RUN   TestSplitThenJoin/19
2020-07-27T13:39:58.2605390Z === RUN   TestSplitThenJoin/20
2020-07-27T13:39:58.2676270Z panic: test timed out after 10m0s
2020-07-27T13:39:58.2678190Z 
2020-07-27T13:39:58.2680040Z goroutine 1243590 [running]:
2020-07-27T13:39:58.2696430Z testing.(*M).startAlarm.func1()
2020-07-27T13:39:58.2767830Z 	/Users/runner/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:1509 +0x11c
2020-07-27T13:39:58.2792660Z created by time.goFunc
2020-07-27T13:39:58.2865060Z 	/Users/runner/hostedtoolcache/go/1.14.6/x64/src/time/sleep.go:168 +0x52
2020-07-27T13:39:58.2866840Z 
2020-07-27T13:39:58.2868580Z goroutine 1 [chan receive, 9 minutes]:
2020-07-27T13:39:58.2872260Z testing.(*T).Run(0xc0000de900, 0x18169c6, 0x11, 0x18318f8, 0x1)
2020-07-27T13:39:58.2875630Z 	/Users/runner/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:1091 +0x739
2020-07-27T13:39:58.2978710Z testing.runTests.func1(0xc0000de900)
2020-07-27T13:39:58.3047570Z 	/Users/runner/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:1334 +0xa7
2020-07-27T13:39:58.3085030Z testing.tRunner(0xc0000de900, 0xc0000bfd38)
2020-07-27T13:39:58.3103840Z 	/Users/runner/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:1039 +0x1ec
2020-07-27T13:39:58.3106690Z testing.runTests(0xc0000b3020, 0x1cf4980, 0x3, 0x3, 0x0)
2020-07-27T13:39:58.3109820Z 	/Users/runner/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:1332 +0x528
2020-07-27T13:39:58.3112550Z testing.(*M).Run(0xc000140300, 0x0)
2020-07-27T13:39:58.3126020Z 	/Users/runner/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:1249 +0x440
2020-07-27T13:39:58.3132110Z main.main()
2020-07-27T13:39:58.3156940Z 	_testmain.go:50 +0x224
2020-07-27T13:39:58.3159100Z 
2020-07-27T13:39:58.3161660Z goroutine 55 [chan receive, 1 minutes]:
2020-07-27T13:39:58.3262610Z testing.(*T).Run(0xc0000df560, 0x182bf25, 0x2, 0x1831910, 0x1)
2020-07-27T13:39:58.3288950Z 	/Users/runner/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:1091 +0x739
2020-07-27T13:39:58.3317210Z github.com/ethersphere/bee/pkg/file_test.TestSplitThenJoin(0xc0000df560)
2020-07-27T13:39:58.3327820Z 	/Users/runner/work/bee/bee/pkg/file/file_test.go:38 +0x89
2020-07-27T13:39:58.3339650Z testing.tRunner(0xc0000df560, 0x18318f8)
2020-07-27T13:39:58.3354580Z 	/Users/runner/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:1039 +0x1ec
2020-07-27T13:39:58.3365520Z created by testing.(*T).Run
2020-07-27T13:39:58.3370570Z 	/Users/runner/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:1090 +0x701
2020-07-27T13:39:58.3438910Z 
2020-07-27T13:39:58.3444720Z goroutine 1244514 [runnable]:
2020-07-27T13:39:58.3469400Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc00009d680, 0x38, 0xc001830fc0, 0x40, 0x40, 0x1)
2020-07-27T13:39:58.3542290Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.2/legacy/bmt.go:472
2020-07-27T13:39:58.3550030Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-07-27T13:39:58.3581940Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.2/legacy/bmt.go:370 +0x41c
2020-07-27T13:39:58.3684790Z 
2020-07-27T13:39:58.3839630Z goroutine 1124315 [runnable]:
2020-07-27T13:39:58.3943040Z github.com/ethersphere/bmt/legacy.(*Hasher).write(0xc00009d680, 0xc004e00680, 0x1000, 0x11a10, 0xc000200168)
2020-07-27T13:39:58.4015120Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.2/legacy/bmt.go:372 +0x43b
2020-07-27T13:39:58.4031150Z github.com/ethersphere/bmt/legacy.(*Hasher).Write(0xc00009d680, 0xc004e00680, 0x1000, 0x11a10, 0x0, 0x0, 0x1)
2020-07-27T13:39:58.4076450Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.2/legacy/bmt.go:331 +0x57
2020-07-27T13:39:58.4097070Z github.com/ethersphere/bee/pkg/file/splitter/internal.(*SimpleSplitterJob).sumLevel(0xc0000d8a00, 0x0, 0x11a10, 0xc004dfc000, 0x1000, 0x1000, 0x1)
2020-07-27T13:39:58.4199590Z 	/Users/runner/work/bee/bee/pkg/file/splitter/internal/job.go:152 +0x4df
2020-07-27T13:39:58.4303790Z github.com/ethersphere/bee/pkg/file/splitter/internal.(*SimpleSplitterJob).writeToLevel(0xc0000d8a00, 0x0, 0xc004dfc000, 0x1000, 0x1000, 0x1000, 0x0)
2020-07-27T13:39:58.4344060Z 	/Users/runner/work/bee/bee/pkg/file/splitter/internal/job.go:119 +0x311
2020-07-27T13:39:58.4348640Z github.com/ethersphere/bee/pkg/file/splitter/internal.(*SimpleSplitterJob).Write(0xc0000d8a00, 0xc004dfc000, 0x1000, 0x1000, 0x1000, 0x0, 0x0)
2020-07-27T13:39:58.4353060Z 	/Users/runner/work/bee/bee/pkg/file/splitter/internal/job.go:87 +0x1cf
2020-07-27T13:39:58.4356780Z github.com/ethersphere/bee/pkg/file/splitter.(*simpleSplitter).Split(0xc000196090, 0x18ea2c0, 0xc000020040, 0x18e4300, 0xc00000e0a0, 0x4000020, 0x0, 0x40, 0x2, 0x11bffd0, ...)
2020-07-27T13:39:58.4486440Z 	/Users/runner/work/bee/bee/pkg/file/splitter/splitter.go:56 +0x421
2020-07-27T13:39:58.4598270Z github.com/ethersphere/bee/pkg/file_test.testSplitThenJoin(0xc0000de000)
2020-07-27T13:39:58.4701850Z 	/Users/runner/work/bee/bee/pkg/file/file_test.go:56 +0x417
2020-07-27T13:39:58.4805560Z testing.tRunner(0xc0000de000, 0x1831910)
2020-07-27T13:39:58.4901370Z 	/Users/runner/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:1039 +0x1ec
2020-07-27T13:39:58.5010230Z created by testing.(*T).Run
2020-07-27T13:39:58.5199480Z 	/Users/runner/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:1090 +0x701
2020-07-27T13:39:58.5211200Z FAIL	github.com/ethersphere/bee/pkg/file	600.982s
```

**Comment by acud** [comment]
closely related to #170 and a possible duplicate. closing and tracking through the second issue
