### ISSUE TITLE
bee 1.16 crashes in salud.go

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#4078]
### Context
1.16 release on mainnet

### Summary
bee crashed with a panic.

### Expected behavior
bee shouldn't crash.

### Actual behavior
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x118abd1]

goroutine 148895616 [running]:
github.com/ethersphere/bee/pkg/salud.(*service).salud.func1.1()
        github.com/ethersphere/bee/pkg/salud/salud.go:137 +0x191
created by github.com/ethersphere/bee/pkg/salud.(*service).salud.func1
        github.com/ethersphere/bee/pkg/salud/salud.go:123 +0x1dc

### Steps to reproduce
No idea, it was just a spontaneous crash.

### Possible solution
None to offer at this time.

**Comment by ldeffenb** [comment]
Looks like PeerSnapshot can return nil, nil...

https://github.com/ethersphere/bee/blob/8292bfc4e174143fab3ad36bccf0719c1bdfc712/pkg/status/status.go#LL109C1-L111C4

**Comment by ldeffenb** [comment]
Lost 2 more nodes overnight.   This fix really needs to get released!
