### ISSUE TITLE
[1.17.2-58e1872e] Panic after "migrated all chunk entries"

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee#4261]
Use case:

I am testing a new Desktop release that updates to Bee 1.17.2

Config:

```
api-addr: 127.0.0.1:1633
debug-api-addr: 127.0.0.1:1635
debug-api-enable: 'true'
swap-enable: 'true'
mainnet: 'true'
full-node: 'false'
cors-allowed-origins: '*'
use-postage-snapshot: 'true'
resolver-options: https://cloudflare-eth.com
data-dir: /Users/****/Library/Application Support/Swarm Desktop/data-dir
password: ****
storage-incentives-enable: 'false'
swap-endpoint: https://xdai.fairdatasociety.org
blockchain-rpc-endpoint: https://xdai.fairdatasociety.org
```

Logs:

```
version: 1.17.2-58e1872e - planned to be supported until 8 November 2023, please follow https://ethswarm.org/

"time"="2023-08-13 09:09:45.551824" "level"="info" "logger"="node" "msg"="bee version" "version"="1.17.2-58e1872e"
"time"="2023-08-13 09:09:45.552106" "level"="warning" "logger"="node" "msg"="clef is not enabled; portability and security of your keys is sub optimal"
"time"="2023-08-13 09:09:45.635035" "level"="info" "logger"="node" "msg"="swarm public key" "public_key"="03a7252fdbe0ae8058b7a8e3887e651322e5def3224e3f5efc98cdece4f4825584"
"time"="2023-08-13 09:09:45.748857" "level"="info" "logger"="node" "msg"="pss public key" "public_key"="0266566429636520f870d1c5b364d127ea0ebf9c885b47ee8fbb0080e84c7a3d79"
"time"="2023-08-13 09:09:45.748879" "level"="info" "logger"="node" "msg"="using ethereum address" "address"="0xE1568B0Bd5D59eA98b2bd22f3b66b7feF5d66B9D"
"time"="2023-08-13 09:09:45.769296" "level"="info" "logger"="node" "msg"="using overlay address" "address"="0b3034dd3bbd8f68df998f5b6c473393ba6a9fb0587c637cc16b56521429f76f"
"time"="2023-08-13 09:09:45.769316" "level"="info" "logger"="node" "msg"="starting with an enabled chain backend"
"time"="2023-08-13 09:09:45.881531" "level"="info" "logger"="node" "msg"="connected to ethereum backend" "version"="Nethermind/v1.20.1+9f39c0c7/linux-x64/dotnet7.0.9"
"time"="2023-08-13 09:09:45.909424" "level"="info" "logger"="node" "msg"="using chain with network network" "chain_id"=100 "network_id"=1
"time"="2023-08-13 09:09:45.929483" "level"="info" "logger"="node" "msg"="starting debug server" "address"="127.0.0.1:1635"
"time"="2023-08-13 09:09:45.997769" "level"="info" "logger"="node" "msg"="using default factory address" "chain_id"=100 "factory_address"="0xC2d5A532cf69AA9A1378737D8ccDEF884B6E7420"
"time"="2023-08-13 09:09:46.083188" "level"="info" "logger"="node/chequebook" "msg"="using existing chequebook" "chequebook_address"="0x9426aB5808C75814e309e3209947E5810FEdf288"
"time"="2023-08-13 09:09:46.111114" "level"="info" "logger"="node" "msg"="cold postage start detected. fetching postage stamp snapshot from swarm"
"time"="2023-08-13 09:09:46.163449" "level"="info" "logger"="migration-step-03" "msg"="starting migration for reconstructing reserve bin IDs, do not interrupt or kill the process..."
"time"="2023-08-13 09:09:46.163596" "level"="info" "logger"="migration-step-03" "msg"="removed all bin index entries"
"time"="2023-08-13 09:09:46.163614" "level"="info" "logger"="migration-step-03" "msg"="removed all bin ids" "total_entries"=0
"time"="2023-08-13 09:09:46.163628" "level"="info" "logger"="migration-step-03" "msg"="found reserve chunk entries, adding new entries" "total_entries"=0
"time"="2023-08-13 09:09:46.163638" "level"="info" "logger"="migration-step-03" "msg"="migrated all chunk entries" "new_size"=0 "missing_chunks"=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x58 pc=0x1056c51f8]

goroutine 66 [running]:
github.com/ethersphere/bee/pkg/storer.New({0x1061f2118, 0x14000f6c0a0}, {0x0, 0x0}, 0x5?)
        github.com/ethersphere/bee/pkg/storer/storer.go:554 +0x4b8
github.com/ethersphere/bee/pkg/node.bootstrapNode({0x1061f2118, 0x14000f6c0a0}, {0x10591ba72, 0x5}, {{0x14000184480?, 0x0?, 0x0?}}, {0x14000042600, 0x20, _}, ...)
        github.com/ethersphere/bee/pkg/node/bootstrap.go:177 +0x107c
github.com/ethersphere/bee/pkg/node.NewBee({0x1061f2118, 0x14000f6c4b0}, {0x10591ba72, 0x5}, 0x14000f90060, {0x1061f4580?, 0x14000208000}, 0x1, {0x1061fdd68, 0x14000f6c460}, ...)
        github.com/ethersphere/bee/pkg/node/node.go:599 +0x2900
github.com/ethersphere/bee/cmd/bee/cmd.buildBeeNode({0x1061f2118, 0x14000f6c4b0}, 0x14000f6c370, 0x140002a7b80?, {0x1061fdd68, 0x14000f6c460})
        github.com/ethersphere/bee/cmd/bee/cmd/start.go:295 +0xf48
github.com/ethersphere/bee/cmd/bee/cmd.buildBeeNodeAsync.func1()
        github.com/ethersphere/bee/cmd/bee/cmd/start.go:200 +0x3c
created by github.com/ethersphere/bee/cmd/bee/cmd.buildBeeNodeAsync
        github.com/ethersphere/bee/cmd/bee/cmd/start.go:199 +0x108
```

**Comment by Cafe137** [comment]
Was this fixed in https://github.com/ethersphere/bee/commit/de2bb6ada0a85f4b63f9990427ff5cfdbec036c8 ?

**Comment by aloknerurkar** [comment]
> Was this fixed in https://github.com/ethersphere/bee/commit/de2bb6ada0a85f4b63f9990427ff5cfdbec036c8 ?

Yes
