### ISSUE TITLE
testnet redistribution panic

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#4347]
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10c40f5]

goroutine 40515322 [running]:
github.com/ethersphere/bee/pkg/storageincentives.(*RedistributionState).SetBalance(0xc004633b20, {0x1b06758?, 0xc00a5145f0?})
	github.com/ethersphere/bee/pkg/storageincentives/redistributionstate.go:217 +0x75
github.com/ethersphere/bee/pkg/storageincentives.(*Agent).handleClaim(0xc003d7cf00, {0x1b06758, 0xc00a5145f0}, 0xc008fe1c00?)
	github.com/ethersphere/bee/pkg/storageincentives/agent.go:351 +0x1dd
github.com/ethersphere/bee/pkg/storageincentives.(*Agent).start.func4({0x1b06758, 0xc00a5145f0})
	github.com/ethersphere/bee/pkg/storageincentives/agent.go:159 +0xa5
created by github.com/ethersphere/bee/pkg/storageincentives.(*events).Publish
	github.com/ethersphere/bee/pkg/storageincentives/events.go:71 +0xea
```

**Comment by istae** [comment]
```
<html>
<body>
<!--StartFragment-->

panic: runtime error: invalid memory address or nil pointer dereference |  
-- | --
  |   | 2023-09-25 15:30:57 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10c40f5] |  
  |   | 2023-09-25 15:30:57 |   |  
  |   | 2023-09-25 15:30:57 | goroutine 262 [running]: |  
  |   | 2023-09-25 15:30:57 | github.com/ethersphere/bee/pkg/storageincentives.(*RedistributionState).SetBalance(0xc00e58c380, {0x1b06758?, 0xc000682460?}) |  
  |   | 2023-09-25 15:30:57 | github.com/ethersphere/bee/pkg/storageincentives/redistributionstate.go:217 +0x75 |  
  |   | 2023-09-25 15:30:57 | github.com/ethersphere/bee/pkg/storageincentives.(*Agent).handleClaim(0xc00ddecf00, {0x1b06758, 0xc000682460}, 0xc009497fa8?) |  
  |   | 2023-09-25 15:30:57 | github.com/ethersphere/bee/pkg/storageincentives/agent.go:351 +0x1dd |  
  |   | 2023-09-25 15:30:57 | github.com/ethersphere/bee/pkg/storageincentives.(*Agent).start.func4({0x1b06758, 0xc000682460}) |  
  |   | 2023-09-25 15:30:57 | github.com/ethersphere/bee/pkg/storageincentives/agent.go:159 +0xa5 |  
  |   | 2023-09-25 15:30:57 | created by github.com/ethersphere/bee/pkg/storageincentives.(*events).Publish |  
  |   | 2023-09-25 15:30:57 | github.com/ethersphere/bee/pkg/storageincentives/events.go:71 +0xea

<!--EndFragment-->
</body>
</html>
```

**Comment by istae** [comment]
looks like `swap-enable` was not turned on
