### ISSUE TITLE
Segmentation fault in reserve code

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee#4829]
```
2024-09-19 00:02:34 panic: runtime error: invalid memory address or nil pointer dereference
2024-09-19 00:02:34 [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xf8da36]
2024-09-19 00:02:34 
2024-09-19 00:02:34 goroutine 655670 [running]:
2024-09-19 00:02:34 github.com/ethersphere/bee/v2/pkg/storer/internal/reserve.(*Reserve).Put(0x0, {0x1b2c078, 0xc00168f1d0}, {0x1b3b640, 0xc005134f00})
2024-09-19 00:02:34     github.com/ethersphere/bee/v2/pkg/storer/internal/reserve/reserve.go:104 +0x76
2024-09-19 00:02:34 github.com/ethersphere/bee/v2/pkg/storer.(*DB).ReservePutter.func1({0x1b2c078?, 0xc00168f1d0?}, {0x1b3b640, 0xc005134f00})
2024-09-19 00:02:34     github.com/ethersphere/bee/v2/pkg/storer/reserve.go:300 +0x53
2024-09-19 00:02:34 github.com/ethersphere/bee/v2/pkg/storage.PutterFunc.Put(0xc0051e5c00?, {0x1b2c078?, 0xc00168f1d0?}, {0x1b3b640?, 0xc005134f00?})
2024-09-19 00:02:34     github.com/ethersphere/bee/v2/pkg/storage/chunkstore.go:56 +0x37
2024-09-19 00:02:34 github.com/ethersphere/bee/v2/pkg/storer.putterWithMetrics.Put({{0x1b1e980, 0xc001368dd0}, {{0xc001434f30}, {0xc001434fc0}, {0x1b3ab48, 0xc00142ce80}, {0x1b3ab48, 0xc00142cf00}, {0x1b32838, 0xc00145e5a0}, ...}, ...}, ...)
2024-09-19 00:02:34     github.com/ethersphere/bee/v2/pkg/storer/metrics.go:181 +0xb4
2024-09-19 00:02:34 github.com/ethersphere/bee/v2/pkg/pusher.(*Service).pushDeferred(0xc0002fc5b0, {0x1b2c078, 0xc00168f1d0}, {0x1b3a9a8?, 0xc0017ba780?}, 0xc00133fdd0)
2024-09-19 00:02:34     github.com/ethersphere/bee/v2/pkg/pusher/pusher.go:261 +0x32b
2024-09-19 00:02:34 github.com/ethersphere/bee/v2/pkg/pusher.(*Service).chunksWorker.func2(0xc00133fdd0)
2024-09-19 00:02:34     github.com/ethersphere/bee/v2/pkg/pusher/pusher.go:163 +0x225
2024-09-19 00:02:34 created by github.com/ethersphere/bee/v2/pkg/pusher.(*Service).chunksWorker in goroutine 41
2024-09-19 00:02:34     github.com/ethersphere/bee/v2/pkg/pusher/pusher.go:230 +0x619
```

**Comment by acha-bill** [comment]
Can you provide the config you ran the node with?
