### ISSUE TITLE
TestSplitThenJoin timing out

### ISSUE THREAD

**Issue by janos** [ethersphere/bee#630]
https://github.com/ethersphere/bee/runs/1041108001#step:10:540
```
2020-08-28T11:07:49.3312390Z === RUN   TestSplitThenJoin/19
2020-08-28T11:07:49.3313310Z panic: test timed out after 10m0s
2020-08-28T11:07:49.3314090Z 
2020-08-28T11:07:49.3315070Z goroutine 1124000 [running]:
2020-08-28T11:07:49.3316010Z testing.(*M).startAlarm.func1()
2020-08-28T11:07:49.3317380Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1609 +0x11f
2020-08-28T11:07:49.3318370Z created by time.goFunc
2020-08-28T11:07:49.3319630Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/time/sleep.go:167 +0x52
2020-08-28T11:07:49.3320190Z 
2020-08-28T11:07:49.3321160Z goroutine 1 [chan receive, 9 minutes]:
2020-08-28T11:07:49.3322370Z testing.(*T).Run(0xc000082780, 0x16c02d7, 0x11, 0x16d7ac0, 0x1)
2020-08-28T11:07:49.3323600Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1160 +0x7cf
2020-08-28T11:07:49.3324610Z testing.runTests.func1(0xc000082780)
2020-08-28T11:07:49.3325880Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1430 +0xa7
2020-08-28T11:07:49.3326970Z testing.tRunner(0xc000082780, 0xc00013fcc8)
2020-08-28T11:07:49.3328280Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1108 +0x203
2020-08-28T11:07:49.3329890Z testing.runTests(0xc000098ec0, 0x19fce00, 0x3, 0x3, 0xbfca574123f984b8, 0x8bb6ca6bae, 0x1a05680, 0xc0000d85c0)
2020-08-28T11:07:49.3331260Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1428 +0x5ab
2020-08-28T11:07:49.3332370Z testing.(*M).Run(0xc0000a6080, 0x0)
2020-08-28T11:07:49.3333700Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1338 +0x4ec
2020-08-28T11:07:49.3334600Z main.main()
2020-08-28T11:07:49.3337110Z 	_testmain.go:49 +0x237
2020-08-28T11:07:49.3338110Z 
2020-08-28T11:07:49.3339100Z goroutine 9 [chan send, 9 minutes]:
2020-08-28T11:07:49.3341030Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000001380, 0x40, 0x83a3098, 0xc0000200c0, 0xc0000286c0, 0xc000028720)
2020-08-28T11:07:49.3342330Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3343640Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3345880Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3346380Z 
2020-08-28T11:07:49.3347320Z goroutine 71 [chan send, 9 minutes]:
2020-08-28T11:07:49.3348890Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000217200, 0x40, 0x83a3098, 0xc00021e280, 0xc0002154a0, 0xc000215500)
2020-08-28T11:07:49.3350280Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3351560Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3352830Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3353360Z 
2020-08-28T11:07:49.3354630Z goroutine 149 [chan receive, 9 minutes]:
2020-08-28T11:07:49.3355930Z testing.(*T).Run(0xc000102a80, 0x16d211f, 0x2, 0x16d7ae0, 0x1)
2020-08-28T11:07:49.3357260Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1160 +0x7cf
2020-08-28T11:07:49.3358610Z github.com/ethersphere/bee/pkg/file_test.TestSplitThenJoin(0xc000102a80)
2020-08-28T11:07:49.3359880Z 	/Users/runner/work/bee/bee/pkg/file/file_test.go:38 +0x89
2020-08-28T11:07:49.3360890Z testing.tRunner(0xc000102a80, 0x16d7ac0)
2020-08-28T11:07:49.3362100Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1108 +0x203
2020-08-28T11:07:49.3363030Z created by testing.(*T).Run
2020-08-28T11:07:49.3364220Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1159 +0x797
2020-08-28T11:07:49.3364740Z 
2020-08-28T11:07:49.3366000Z goroutine 6 [chan send, 9 minutes]:
2020-08-28T11:07:49.3371210Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000001200, 0x40, 0x83a3098, 0xc000020080, 0xc000028420, 0xc000028480)
2020-08-28T11:07:49.3373520Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3374790Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3375890Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3376340Z 
2020-08-28T11:07:49.3377220Z goroutine 68 [chan send, 9 minutes]:
2020-08-28T11:07:49.3378750Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000216f00, 0x40, 0x83a3098, 0xc00021e240, 0xc0002151a0, 0xc000215200)
2020-08-28T11:07:49.3379990Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3381200Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3382320Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3382760Z 
2020-08-28T11:07:49.3383730Z goroutine 138 [chan send, 9 minutes]:
2020-08-28T11:07:49.3385290Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000001380, 0x1000, 0x83a3098, 0xc00021e2c0, 0xc000290420, 0xc0002904e0)
2020-08-28T11:07:49.3386510Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3387800Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3389000Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3389610Z 
2020-08-28T11:07:49.3390550Z goroutine 37 [chan send, 9 minutes]:
2020-08-28T11:07:49.3392150Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000082c00, 0x40, 0x83a3098, 0xc0000d8640, 0xc000290480, 0xc0002904e0)
2020-08-28T11:07:49.3393400Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3394960Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3396180Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3397010Z 
2020-08-28T11:07:49.3400300Z goroutine 74 [chan send, 9 minutes]:
2020-08-28T11:07:49.3402110Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000217500, 0x40, 0x83a3098, 0xc00021e2c0, 0xc0002157a0, 0xc000215800)
2020-08-28T11:07:49.3403370Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3404670Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3405860Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3407270Z 
2020-08-28T11:07:49.3408260Z goroutine 77 [chan send, 9 minutes]:
2020-08-28T11:07:49.3409830Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000217980, 0x40, 0x83a3098, 0xc00021e300, 0xc000215b00, 0xc000215b60)
2020-08-28T11:07:49.3411120Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3412420Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3413630Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3414230Z 
2020-08-28T11:07:49.3415180Z goroutine 80 [chan send, 9 minutes]:
2020-08-28T11:07:49.3416750Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000217c80, 0x40, 0x83a3098, 0xc00021e340, 0xc000215e00, 0xc000215e60)
2020-08-28T11:07:49.3418010Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3419290Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3420570Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3421100Z 
2020-08-28T11:07:49.3422070Z goroutine 83 [chan send, 9 minutes]:
2020-08-28T11:07:49.3423610Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000316000, 0x40, 0x83a3098, 0xc00021e380, 0xc000318180, 0xc0003181e0)
2020-08-28T11:07:49.3425180Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3426530Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3427690Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3428180Z 
2020-08-28T11:07:49.3429110Z goroutine 85 [chan send, 9 minutes]:
2020-08-28T11:07:49.3430730Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000001680, 0x40, 0x83a3098, 0xc00021e3c0, 0xc000318360, 0xc0003183c0)
2020-08-28T11:07:49.3432000Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3433210Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3434400Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3434880Z 
2020-08-28T11:07:49.3435770Z goroutine 40 [chan send, 9 minutes]:
2020-08-28T11:07:49.3437300Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000082d80, 0x40, 0x83a3098, 0xc0000d8680, 0xc000290720, 0xc000290780)
2020-08-28T11:07:49.3438490Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3439700Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3440860Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3441340Z 
2020-08-28T11:07:49.3442230Z goroutine 88 [chan send, 9 minutes]:
2020-08-28T11:07:49.3443770Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000316480, 0x400, 0x83a3098, 0xc00021e400, 0xc000318600, 0xc000318660)
2020-08-28T11:07:49.3444980Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3446200Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3447370Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3447850Z 
2020-08-28T11:07:49.3448730Z goroutine 13 [chan send, 9 minutes]:
2020-08-28T11:07:49.3450240Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000001800, 0x40, 0x83a3098, 0xc000020100, 0xc000028a80, 0xc000028ae0)
2020-08-28T11:07:49.3451430Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3454290Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3455940Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3456440Z 
2020-08-28T11:07:49.3457610Z goroutine 91 [chan send, 9 minutes]:
2020-08-28T11:07:49.3459310Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000316780, 0x400, 0x83a3098, 0xc00021e440, 0xc0003188a0, 0xc000318900)
2020-08-28T11:07:49.3460550Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3462490Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3463650Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3464100Z 
2020-08-28T11:07:49.3465040Z goroutine 94 [chan send, 9 minutes]:
2020-08-28T11:07:49.3466570Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000316c00, 0x400, 0x83a3098, 0xc00021e480, 0xc000318c00, 0xc000318c60)
2020-08-28T11:07:49.3467770Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3475530Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3476900Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3477460Z 
2020-08-28T11:07:49.3478430Z goroutine 97 [chan send, 9 minutes]:
2020-08-28T11:07:49.3480050Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000316f00, 0x400, 0x83a3098, 0xc00021e4c0, 0xc000318ea0, 0xc000318f00)
2020-08-28T11:07:49.3481360Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3482690Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3484190Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3484830Z 
2020-08-28T11:07:49.3485780Z goroutine 100 [chan send, 9 minutes]:
2020-08-28T11:07:49.3487370Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000317200, 0x400, 0x83a3098, 0xc00021e500, 0xc000319140, 0xc0003191a0)
2020-08-28T11:07:49.3488700Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3489980Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3491200Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3491780Z 
2020-08-28T11:07:49.3492700Z goroutine 103 [chan send, 9 minutes]:
2020-08-28T11:07:49.3494360Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000317500, 0x400, 0x83a3098, 0xc00021e540, 0xc000319440, 0xc0003194a0)
2020-08-28T11:07:49.3506930Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3508470Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3511490Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3511810Z 
2020-08-28T11:07:49.3512340Z goroutine 106 [chan send, 9 minutes]:
2020-08-28T11:07:49.3514280Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000317800, 0x400, 0x83a3098, 0xc00021e580, 0xc000319740, 0xc0003197a0)
2020-08-28T11:07:49.3515130Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3515820Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3516460Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3516720Z 
2020-08-28T11:07:49.3517210Z goroutine 44 [chan send, 9 minutes]:
2020-08-28T11:07:49.3518070Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000083200, 0x400, 0x83a3098, 0xc00021e000, 0xc000318120, 0xc0003181e0)
2020-08-28T11:07:49.3518760Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3519420Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3520050Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3520300Z 
2020-08-28T11:07:49.3520770Z goroutine 47 [chan send, 9 minutes]:
2020-08-28T11:07:49.3523010Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000316480, 0x400, 0x83a3098, 0xc00021e040, 0xc0003184e0, 0xc000318540)
2020-08-28T11:07:49.3524370Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3525360Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3526000Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3526250Z 
2020-08-28T11:07:49.3526730Z goroutine 114 [chan send, 9 minutes]:
2020-08-28T11:07:49.3527590Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000316c00, 0x400, 0x83a3098, 0xc00021e0c0, 0xc0003187e0, 0xc000318840)
2020-08-28T11:07:49.3528870Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3529550Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3530210Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3530430Z 
2020-08-28T11:07:49.3530920Z goroutine 117 [chan send, 9 minutes]:
2020-08-28T11:07:49.3531800Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000317200, 0x400, 0x83a3098, 0xc00021e100, 0xc000318ae0, 0xc000318b40)
2020-08-28T11:07:49.3532480Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3533140Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3533760Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3533980Z 
2020-08-28T11:07:49.3534470Z goroutine 120 [chan send, 9 minutes]:
2020-08-28T11:07:49.3535340Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000082900, 0x400, 0x83a3098, 0xc00021e140, 0xc000318de0, 0xc000318e40)
2020-08-28T11:07:49.3536010Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3536670Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3537280Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3537520Z 
2020-08-28T11:07:49.3538000Z goroutine 123 [chan send, 9 minutes]:
2020-08-28T11:07:49.3538870Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000082d80, 0x1000, 0x83a3098, 0xc00021e180, 0xc0003190e0, 0xc0003191a0)
2020-08-28T11:07:49.3539530Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3540190Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3540800Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3541050Z 
2020-08-28T11:07:49.3541520Z goroutine 126 [chan send, 9 minutes]:
2020-08-28T11:07:49.3542400Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000083500, 0x1000, 0x83a3098, 0xc00021e1c0, 0xc0003193e0, 0xc0003194a0)
2020-08-28T11:07:49.3543050Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3543990Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3544810Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3545070Z 
2020-08-28T11:07:49.3545550Z goroutine 129 [chan send, 9 minutes]:
2020-08-28T11:07:49.3546410Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000083800, 0x1000, 0x83a3098, 0xc00021e200, 0xc000319a40, 0xc000319aa0)
2020-08-28T11:07:49.3547060Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3547740Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3548370Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3548590Z 
2020-08-28T11:07:49.3549090Z goroutine 132 [chan send, 9 minutes]:
2020-08-28T11:07:49.3549940Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000083b00, 0x1000, 0x83a3098, 0xc00021e240, 0xc000319d40, 0xc000319da0)
2020-08-28T11:07:49.3550600Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3551260Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3551870Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3552090Z 
2020-08-28T11:07:49.3553390Z goroutine 135 [chan send, 9 minutes]:
2020-08-28T11:07:49.3554690Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000001200, 0x1000, 0x83a3098, 0xc00021e280, 0xc000290000, 0xc000290180)
2020-08-28T11:07:49.3555380Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3556040Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3556660Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3557430Z 
2020-08-28T11:07:49.3557920Z goroutine 141 [chan send, 9 minutes]:
2020-08-28T11:07:49.3558970Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000001800, 0x1000, 0x83a3098, 0xc00021e300, 0xc000290960, 0xc0002909c0)
2020-08-28T11:07:49.3559680Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3560330Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3560940Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3561210Z 
2020-08-28T11:07:49.3561690Z goroutine 144 [chan send, 9 minutes]:
2020-08-28T11:07:49.3562530Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000001b00, 0x1000, 0x83a3098, 0xc00021e340, 0xc000290cc0, 0xc000290d20)
2020-08-28T11:07:49.3567020Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3567940Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3568880Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3571960Z 
2020-08-28T11:07:49.3575480Z goroutine 147 [chan send, 9 minutes]:
2020-08-28T11:07:49.3577840Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000001e00, 0x1000, 0x83a3098, 0xc00021e380, 0xc000290fc0, 0xc000291020)
2020-08-28T11:07:49.3579310Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3581110Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3635300Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3635920Z 
2020-08-28T11:07:49.3637310Z goroutine 23 [chan send, 9 minutes]:
2020-08-28T11:07:49.3639220Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000216000, 0x1000, 0x83a3098, 0xc0000d8000, 0xc0000283c0, 0xc000028480)
2020-08-28T11:07:49.3640520Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3641810Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3643110Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3643640Z 
2020-08-28T11:07:49.3644600Z goroutine 26 [chan send, 9 minutes]:
2020-08-28T11:07:49.3646250Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000216480, 0x1000, 0x83a3098, 0xc0000d8640, 0xc000028720, 0xc000028780)
2020-08-28T11:07:49.3647570Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3648880Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3654770Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3655350Z 
2020-08-28T11:07:49.3655890Z goroutine 29 [chan send, 9 minutes]:
2020-08-28T11:07:49.3656790Z github.com/ethersphere/bee/pkg/file_test.reader(0xc000216780, 0x1000, 0x83a3098, 0xc0000d8680, 0xc0000289c0, 0xc000028a20)
2020-08-28T11:07:49.3657480Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:236 +0x2fa
2020-08-28T11:07:49.3658160Z created by github.com/ethersphere/bee/pkg/file_test.TestCopyBuffer.func1
2020-08-28T11:07:49.3658820Z 	/Users/runner/work/bee/bee/pkg/file/buffer_test.go:170 +0x5b8
2020-08-28T11:07:49.3659080Z 
2020-08-28T11:07:49.3659520Z goroutine 51072 [running]:
2020-08-28T11:07:49.3660080Z 	goroutine running on other thread; stack unavailable
2020-08-28T11:07:49.3660560Z created by testing.(*T).Run
2020-08-28T11:07:49.3661240Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1159 +0x797
2020-08-28T11:07:49.3661860Z FAIL	github.com/ethersphere/bee/pkg/file	601.020s
```

**Comment by janos** [comment]
It looks like that this is a deadlock on buffer_test.go:236 when writing to a channel that is not read from.
