### ISSUE TITLE
TestAllVectors timing out

### ISSUE THREAD

**Issue by janos** [ethersphere/bee#631]
https://github.com/ethersphere/bee/runs/1041108001#step:10:850

2020-08-28T11:07:50.6784380Z === RUN   TestAllVectors/data_length_67108896,_vector_20
2020-08-28T11:07:50.6788900Z panic: test timed out after 10m0s
2020-08-28T11:07:50.6791100Z 
2020-08-28T11:07:50.6793820Z goroutine 1322488 [running]:
2020-08-28T11:07:50.6822390Z testing.(*M).startAlarm.func1()
2020-08-28T11:07:50.6926810Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1609 +0x11f
2020-08-28T11:07:50.6935630Z created by time.goFunc
2020-08-28T11:07:50.6955900Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/time/sleep.go:167 +0x52
2020-08-28T11:07:50.6963850Z 
2020-08-28T11:07:50.6970870Z goroutine 1 [chan receive, 9 minutes]:
2020-08-28T11:07:50.6987360Z testing.(*T).Run(0xc000001c80, 0x16bed77, 0xe, 0x16d7848, 0x1)
2020-08-28T11:07:50.7017180Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1160 +0x7cf
2020-08-28T11:07:50.7020130Z testing.runTests.func1(0xc000001c80)
2020-08-28T11:07:50.7023420Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1430 +0xa7
2020-08-28T11:07:50.7026420Z testing.tRunner(0xc000001c80, 0xc000107cc8)
2020-08-28T11:07:50.7029440Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1108 +0x203
2020-08-28T11:07:50.7032670Z testing.runTests(0xc00000f040, 0x19fc760, 0x5, 0x5, 0xbfca5741859467e0, 0x8bb4e8e21a, 0x1a042a0, 0xc0000212c0)
2020-08-28T11:07:50.7035850Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1428 +0x5ab
2020-08-28T11:07:50.7039140Z testing.(*M).Run(0xc000186300, 0x0)
2020-08-28T11:07:50.7042350Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1338 +0x4ec
2020-08-28T11:07:50.7045090Z main.main()
2020-08-28T11:07:50.7047710Z 	_testmain.go:53 +0x237
2020-08-28T11:07:50.7048520Z 
2020-08-28T11:07:50.7050260Z goroutine 46 [chan receive, 1 minutes]:
2020-08-28T11:07:50.7051490Z testing.(*T).Run(0xc0001d1c80, 0xc0000263e0, 0x1f, 0xc000020040, 0x2)
2020-08-28T11:07:50.7052390Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1160 +0x7cf
2020-08-28T11:07:50.7053280Z github.com/ethersphere/bee/pkg/file/pipeline_test.TestAllVectors(0xc0001d1c80)
2020-08-28T11:07:50.7054300Z 	/Users/runner/work/bee/bee/pkg/file/pipeline/pipeline_test.go:60 +0xa9
2020-08-28T11:07:50.7055050Z testing.tRunner(0xc0001d1c80, 0x16d7848)
2020-08-28T11:07:50.7056260Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1108 +0x203
2020-08-28T11:07:50.7057540Z created by testing.(*T).Run
2020-08-28T11:07:50.7059170Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1159 +0x797
2020-08-28T11:07:50.7059800Z 
2020-08-28T11:07:50.7060750Z goroutine 1323022 [runnable]:
2020-08-28T11:07:50.7062270Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc0001d20c0, 0x4, 0xc001d27740, 0x40, 0x40, 0x1)
2020-08-28T11:07:50.7063730Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.2/legacy/bmt.go:472
2020-08-28T11:07:50.7065020Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-08-28T11:07:50.7066410Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.2/legacy/bmt.go:370 +0x47b
2020-08-28T11:07:50.7067070Z 
2020-08-28T11:07:50.7068000Z goroutine 1323025 [runnable]:
2020-08-28T11:07:50.7069510Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc0001d20c0, 0x7, 0xc001d27800, 0x40, 0x40, 0x1)
2020-08-28T11:07:50.7070940Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.2/legacy/bmt.go:472
2020-08-28T11:07:50.7072240Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-08-28T11:07:50.7075400Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.2/legacy/bmt.go:370 +0x47b
2020-08-28T11:07:50.7076200Z 
2020-08-28T11:07:50.7077380Z goroutine 1323023 [runnable]:
2020-08-28T11:07:50.7079100Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc0001d20c0, 0x5, 0xc001d27780, 0x40, 0x40, 0x1)
2020-08-28T11:07:50.7080560Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.2/legacy/bmt.go:472
2020-08-28T11:07:50.7081850Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-08-28T11:07:50.7084430Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.2/legacy/bmt.go:370 +0x47b
2020-08-28T11:07:50.7085040Z 
2020-08-28T11:07:50.7085960Z goroutine 1123658 [runnable]:
2020-08-28T11:07:50.7087440Z github.com/ethersphere/bmt/legacy.(*Hasher).write(0xc0001d20c0, 0xc000181308, 0x1000, 0x1000, 0xc0001d20d0)
2020-08-28T11:07:50.7088950Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.2/legacy/bmt.go:372 +0x49a
2020-08-28T11:07:50.7090620Z github.com/ethersphere/bmt/legacy.(*Hasher).Write(0xc0001d20c0, 0xc000181308, 0x1000, 0x1000, 0x0, 0x0, 0xc000103ce8)
2020-08-28T11:07:50.7092100Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.2/legacy/bmt.go:331 +0x57
2020-08-28T11:07:50.7093780Z github.com/ethersphere/bee/pkg/file/pipeline.(*bmtWriter).chainWrite(0xc00000e1a0, 0xc0067dc360, 0xc008cf0000, 0x342a020)
2020-08-28T11:07:50.7095140Z 	/Users/runner/work/bee/bee/pkg/file/pipeline/bmt_writer.go:38 +0x19a
2020-08-28T11:07:50.7097140Z github.com/ethersphere/bee/pkg/file/pipeline.(*chunkFeeder).Write(0xc000020240, 0xc00811a000, 0x4000020, 0x4000020, 0x2, 0x109a500, 0x174dfe0)
2020-08-28T11:07:50.7100520Z 	/Users/runner/work/bee/bee/pkg/file/pipeline/chunkfeeder_writer.go:77 +0x6cc
2020-08-28T11:07:50.7159450Z github.com/ethersphere/bee/pkg/file/pipeline_test.TestAllVectors.func1(0xc000544000)
2020-08-28T11:07:50.7161330Z 	/Users/runner/work/bee/bee/pkg/file/pipeline/pipeline_test.go:64 +0x13f
2020-08-28T11:07:50.7162520Z testing.tRunner(0xc000544000, 0xc000020040)
2020-08-28T11:07:50.7163920Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1108 +0x203
2020-08-28T11:07:50.7164990Z created by testing.(*T).Run
2020-08-28T11:07:50.7166300Z 	/Users/runner/hostedtoolcache/go/1.15.0/x64/src/testing/testing.go:1159 +0x797
2020-08-28T11:07:50.7166910Z 
2020-08-28T11:07:50.7167840Z goroutine 1323024 [runnable]:
2020-08-28T11:07:50.7169360Z github.com/ethersphere/bmt/legacy.(*Hasher).writeSection(0xc0001d20c0, 0x6, 0xc001d277c0, 0x40, 0x40, 0x1)
2020-08-28T11:07:50.7170850Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.2/legacy/bmt.go:472
2020-08-28T11:07:50.7172130Z created by github.com/ethersphere/bmt/legacy.(*Hasher).write
2020-08-28T11:07:50.7173550Z 	/Users/runner/go/pkg/mod/github.com/ethersphere/bmt@v0.1.2/legacy/bmt.go:370 +0x47b
2020-08-28T11:07:50.7174860Z FAIL	github.com/ethersphere/bee/pkg/file/pipeline	600.869s

**Comment by janos** [comment]
It looks like that this is a deadlock on buffer_test.go:236 when writing to a channel that is not read from.

**Comment by Eknir** [comment]
Can this be closed?

**Comment by Eknir** [comment]
@janos , bump

**Comment by janos** [comment]
Yes, this can be closed.
