### ISSUE TITLE
go panic in retrieval unit test

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/bee#764]
happened in ci in test with race detector
```
=== RUN   TestDelivery
--- PASS: TestDelivery (0.01s)
=== RUN   TestRetrieveChunk
=== RUN   TestRetrieveChunk/downstream
=== RUN   TestRetrieveChunk/upstream
--- PASS: TestRetrieveChunk (0.00s)
    --- PASS: TestRetrieveChunk/downstream (0.00s)
    --- PASS: TestRetrieveChunk/upstream (0.00s)
PASS
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4afbd41]

goroutine 38 [running]:
github.com/ethersphere/bee/pkg/retrieval.(*Service).handler(0xc0000cc000, 0x4e4a880, 0xc0004ba150, 0xc000094100, 0x1, 0x8, 0x4e4d940, 0xc0000a82a0, 0x0, 0x0)
	/Users/runner/work/bee/bee/pkg/retrieval/retrieval.go:261 +0x681
github.com/ethersphere/bee/pkg/p2p/streamtest.(*Recorder).NewStream.func1(0xc0000c0240, 0xc0000be0b0, 0x4e4a840, 0xc00008e780, 0xc000094100, 0x1, 0x8, 0xc0000a82a0)
	/Users/runner/work/bee/bee/pkg/p2p/streamtest/streamtest.go:99 +0x102
created by github.com/ethersphere/bee/pkg/p2p/streamtest.(*Recorder).NewStream
	/Users/runner/work/bee/bee/pkg/p2p/streamtest/streamtest.go:96 +0x875
FAIL	github.com/ethersphere/bee/pkg/retrieval	0.569s
```

line 261 is
```go
chunk, err := s.storer.Get(ctx, storage.ModeGetRequest, swarm.NewAddress(req.Addr))
```
~so maybe `s.storer` was nil~

**Comment by acud** [comment]
my guess would be that it is more likely that `req.Addr` was `nil`

**Comment by acud** [comment]
i bisected this to be from https://github.com/ethersphere/bee/commit/ed2d6085512122072e63d937ad89a6535426590e

**Comment by acud** [comment]
actually it was indeed `storer` that was `nil`
